// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authenticationService/proto/authenticationServiceAPI.proto

package authenticationService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginAuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAuthRequest) Reset()         { *m = LoginAuthRequest{} }
func (m *LoginAuthRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAuthRequest) ProtoMessage()    {}
func (*LoginAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6991cbd76a21bcaf, []int{0}
}

func (m *LoginAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAuthRequest.Unmarshal(m, b)
}
func (m *LoginAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAuthRequest.Marshal(b, m, deterministic)
}
func (m *LoginAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAuthRequest.Merge(m, src)
}
func (m *LoginAuthRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAuthRequest.Size(m)
}
func (m *LoginAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAuthRequest proto.InternalMessageInfo

func (m *LoginAuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginAuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginAuthResponse struct {
	Permissions          string   `protobuf:"bytes,1,opt,name=permissions,proto3" json:"permissions,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAuthResponse) Reset()         { *m = LoginAuthResponse{} }
func (m *LoginAuthResponse) String() string { return proto.CompactTextString(m) }
func (*LoginAuthResponse) ProtoMessage()    {}
func (*LoginAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6991cbd76a21bcaf, []int{1}
}

func (m *LoginAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAuthResponse.Unmarshal(m, b)
}
func (m *LoginAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAuthResponse.Marshal(b, m, deterministic)
}
func (m *LoginAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAuthResponse.Merge(m, src)
}
func (m *LoginAuthResponse) XXX_Size() int {
	return xxx_messageInfo_LoginAuthResponse.Size(m)
}
func (m *LoginAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAuthResponse proto.InternalMessageInfo

func (m *LoginAuthResponse) GetPermissions() string {
	if m != nil {
		return m.Permissions
	}
	return ""
}

func (m *LoginAuthResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginAuthRequest)(nil), "LoginAuthRequest")
	proto.RegisterType((*LoginAuthResponse)(nil), "LoginAuthResponse")
}

func init() {
	proto.RegisterFile("authenticationService/proto/authenticationServiceAPI.proto", fileDescriptor_6991cbd76a21bcaf)
}

var fileDescriptor_6991cbd76a21bcaf = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x4a, 0x2c, 0x2d, 0xc9,
	0x48, 0xcd, 0x2b, 0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x0b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c,
	0x4e, 0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xc7, 0x2a, 0xe7, 0x18, 0xe0, 0xa9, 0x07, 0x96,
	0x56, 0xf2, 0xe2, 0x12, 0xf0, 0xc9, 0x4f, 0xcf, 0xcc, 0x73, 0x2c, 0x2d, 0xc9, 0x08, 0x4a, 0x2d,
	0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe2, 0xe2, 0x28, 0x2d, 0x4e, 0x2d, 0xca, 0x4b, 0xcc, 0x4d,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x41, 0x72, 0x05, 0x89, 0xc5, 0xc5, 0xe5,
	0xf9, 0x45, 0x29, 0x12, 0x4c, 0x10, 0x39, 0x18, 0x5f, 0x29, 0x82, 0x4b, 0x10, 0xc9, 0xac, 0xe2,
	0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x05, 0x2e, 0xee, 0x82, 0xd4, 0xa2, 0xdc, 0xcc, 0xe2, 0xe2,
	0xcc, 0xfc, 0xbc, 0x62, 0xa8, 0x79, 0xc8, 0x42, 0x42, 0x8a, 0x5c, 0x3c, 0x89, 0xc9, 0xc9, 0xa9,
	0xc5, 0xc5, 0xf1, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x50, 0x63, 0xb9, 0x21, 0x62, 0x21, 0x20, 0x21,
	0x23, 0x5f, 0x2e, 0x51, 0x47, 0x6c, 0xfe, 0x10, 0x32, 0xe1, 0xe2, 0x84, 0x5b, 0x29, 0x24, 0xa8,
	0x87, 0xee, 0x15, 0x29, 0x21, 0x3d, 0x0c, 0x17, 0x29, 0x31, 0x38, 0x19, 0x47, 0x19, 0xe2, 0x09,
	0x32, 0x6b, 0xac, 0x72, 0x49, 0x6c, 0x60, 0x49, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd2,
	0x72, 0x28, 0x30, 0x6e, 0x01, 0x00, 0x00,
}
