# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.fetchDataAPI_pb2 as fetchDataAPI__pb2


class FetchDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchDataService = channel.unary_unary(
                '/fetchData.FetchData/FetchDataService',
                request_serializer=fetchDataAPI__pb2.FetchDataRequestMessage.SerializeToString,
                response_deserializer=fetchDataAPI__pb2.FetchDataResponseMessage.FromString,
                )


class FetchDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchDataService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FetchDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchDataService': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchDataService,
                    request_deserializer=fetchDataAPI__pb2.FetchDataRequestMessage.FromString,
                    response_serializer=fetchDataAPI__pb2.FetchDataResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fetchData.FetchData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FetchData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchDataService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fetchData.FetchData/FetchDataService',
            fetchDataAPI__pb2.FetchDataRequestMessage.SerializeToString,
            fetchDataAPI__pb2.FetchDataResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
