// Code generated by protoc-gen-go. DO NOT EDIT.
// source: powerEstimationSP/proto/powerEstimationAPI.proto

package powerEstimation

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ModelTypeEnum int32

const (
	ModelTypeEnum_UNKNOWN   ModelTypeEnum = 0
	ModelTypeEnum_OPENWATER ModelTypeEnum = 1
	ModelTypeEnum_ICE       ModelTypeEnum = 2
)

var ModelTypeEnum_name = map[int32]string{
	0: "UNKNOWN",
	1: "OPENWATER",
	2: "ICE",
}

var ModelTypeEnum_value = map[string]int32{
	"UNKNOWN":   0,
	"OPENWATER": 1,
	"ICE":       2,
}

func (x ModelTypeEnum) String() string {
	return proto.EnumName(ModelTypeEnum_name, int32(x))
}

func (ModelTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_daf15462637bc3b8, []int{0}
}

type ServicePackageRequestMessage struct {
	InputFile            string        `protobuf:"bytes,1,opt,name=input_file,json=inputFile,proto3" json:"input_file,omitempty"`
	ModelType            ModelTypeEnum `protobuf:"varint,2,opt,name=model_type,json=modelType,proto3,enum=powerEstimation.ModelTypeEnum" json:"model_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ServicePackageRequestMessage) Reset()         { *m = ServicePackageRequestMessage{} }
func (m *ServicePackageRequestMessage) String() string { return proto.CompactTextString(m) }
func (*ServicePackageRequestMessage) ProtoMessage()    {}
func (*ServicePackageRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf15462637bc3b8, []int{0}
}

func (m *ServicePackageRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServicePackageRequestMessage.Unmarshal(m, b)
}
func (m *ServicePackageRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServicePackageRequestMessage.Marshal(b, m, deterministic)
}
func (m *ServicePackageRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServicePackageRequestMessage.Merge(m, src)
}
func (m *ServicePackageRequestMessage) XXX_Size() int {
	return xxx_messageInfo_ServicePackageRequestMessage.Size(m)
}
func (m *ServicePackageRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServicePackageRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServicePackageRequestMessage proto.InternalMessageInfo

func (m *ServicePackageRequestMessage) GetInputFile() string {
	if m != nil {
		return m.InputFile
	}
	return ""
}

func (m *ServicePackageRequestMessage) GetModelType() ModelTypeEnum {
	if m != nil {
		return m.ModelType
	}
	return ModelTypeEnum_UNKNOWN
}

type EstimateResponseMessage struct {
	PowerEstimate        []float32 `protobuf:"fixed32,1,rep,packed,name=power_estimate,json=powerEstimate,proto3" json:"power_estimate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EstimateResponseMessage) Reset()         { *m = EstimateResponseMessage{} }
func (m *EstimateResponseMessage) String() string { return proto.CompactTextString(m) }
func (*EstimateResponseMessage) ProtoMessage()    {}
func (*EstimateResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf15462637bc3b8, []int{1}
}

func (m *EstimateResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimateResponseMessage.Unmarshal(m, b)
}
func (m *EstimateResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimateResponseMessage.Marshal(b, m, deterministic)
}
func (m *EstimateResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimateResponseMessage.Merge(m, src)
}
func (m *EstimateResponseMessage) XXX_Size() int {
	return xxx_messageInfo_EstimateResponseMessage.Size(m)
}
func (m *EstimateResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimateResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EstimateResponseMessage proto.InternalMessageInfo

func (m *EstimateResponseMessage) GetPowerEstimate() []float32 {
	if m != nil {
		return m.PowerEstimate
	}
	return nil
}

type EvaluateResponseMessage struct {
	PowerEstimate        []float32 `protobuf:"fixed32,1,rep,packed,name=power_estimate,json=powerEstimate,proto3" json:"power_estimate,omitempty"`
	PowerActual          []float32 `protobuf:"fixed32,2,rep,packed,name=power_actual,json=powerActual,proto3" json:"power_actual,omitempty"`
	SpeedOverGround      []float32 `protobuf:"fixed32,3,rep,packed,name=speed_over_ground,json=speedOverGround,proto3" json:"speed_over_ground,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EvaluateResponseMessage) Reset()         { *m = EvaluateResponseMessage{} }
func (m *EvaluateResponseMessage) String() string { return proto.CompactTextString(m) }
func (*EvaluateResponseMessage) ProtoMessage()    {}
func (*EvaluateResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf15462637bc3b8, []int{2}
}

func (m *EvaluateResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvaluateResponseMessage.Unmarshal(m, b)
}
func (m *EvaluateResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvaluateResponseMessage.Marshal(b, m, deterministic)
}
func (m *EvaluateResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvaluateResponseMessage.Merge(m, src)
}
func (m *EvaluateResponseMessage) XXX_Size() int {
	return xxx_messageInfo_EvaluateResponseMessage.Size(m)
}
func (m *EvaluateResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EvaluateResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EvaluateResponseMessage proto.InternalMessageInfo

func (m *EvaluateResponseMessage) GetPowerEstimate() []float32 {
	if m != nil {
		return m.PowerEstimate
	}
	return nil
}

func (m *EvaluateResponseMessage) GetPowerActual() []float32 {
	if m != nil {
		return m.PowerActual
	}
	return nil
}

func (m *EvaluateResponseMessage) GetSpeedOverGround() []float32 {
	if m != nil {
		return m.SpeedOverGround
	}
	return nil
}

func init() {
	proto.RegisterEnum("powerEstimation.ModelTypeEnum", ModelTypeEnum_name, ModelTypeEnum_value)
	proto.RegisterType((*ServicePackageRequestMessage)(nil), "powerEstimation.ServicePackageRequestMessage")
	proto.RegisterType((*EstimateResponseMessage)(nil), "powerEstimation.EstimateResponseMessage")
	proto.RegisterType((*EvaluateResponseMessage)(nil), "powerEstimation.EvaluateResponseMessage")
}

func init() {
	proto.RegisterFile("powerEstimationSP/proto/powerEstimationAPI.proto", fileDescriptor_daf15462637bc3b8)
}

var fileDescriptor_daf15462637bc3b8 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xdf, 0x4b, 0xfa, 0x50,
	0x18, 0xc6, 0xbf, 0x9b, 0xf0, 0x95, 0xbd, 0xe6, 0x8f, 0x0e, 0x84, 0x23, 0x32, 0x4c, 0x08, 0x86,
	0x90, 0x86, 0x75, 0x1b, 0x24, 0xb1, 0x42, 0xc2, 0x39, 0xa6, 0xe1, 0xe5, 0x58, 0xfa, 0x26, 0xa3,
	0x6d, 0xe7, 0xb4, 0x73, 0xb6, 0x10, 0xba, 0xeb, 0x0f, 0xe8, 0x5f, 0x8e, 0x8e, 0x1a, 0x3a, 0xab,
	0x8b, 0xe8, 0x72, 0xcf, 0xf3, 0xe1, 0x79, 0xd8, 0xfb, 0x1c, 0x38, 0x65, 0xf4, 0x19, 0x63, 0x93,
	0x0b, 0x3f, 0xf4, 0x84, 0x4f, 0xa3, 0xa1, 0xdd, 0x66, 0x31, 0x15, 0xb4, 0x9d, 0xd1, 0xbb, 0x76,
	0xaf, 0x25, 0x0d, 0x52, 0xce, 0x38, 0x8d, 0x17, 0x38, 0x18, 0x62, 0x9c, 0xfa, 0x13, 0xb4, 0xbd,
	0xc9, 0xa3, 0x37, 0x43, 0x07, 0x9f, 0x12, 0xe4, 0xa2, 0x8f, 0x9c, 0x7b, 0x33, 0x24, 0x35, 0x00,
	0x3f, 0x62, 0x89, 0x70, 0x1f, 0xfc, 0x00, 0x75, 0xa5, 0xae, 0x18, 0x9a, 0xa3, 0x49, 0xe5, 0xda,
	0x0f, 0x90, 0x5c, 0x00, 0x84, 0x74, 0x8a, 0x81, 0x2b, 0xe6, 0x0c, 0x75, 0xb5, 0xae, 0x18, 0xa5,
	0xce, 0x61, 0x2b, 0x53, 0xd2, 0xea, 0x7f, 0x20, 0xa3, 0x39, 0x43, 0x33, 0x4a, 0x42, 0x47, 0x0b,
	0x57, 0x9f, 0x8d, 0x4b, 0xa8, 0x2e, 0x31, 0x74, 0x90, 0x33, 0x1a, 0x71, 0x5c, 0x15, 0x1f, 0x43,
	0x49, 0xc6, 0xb8, 0xb8, 0x04, 0x74, 0xa5, 0x9e, 0x33, 0x54, 0xa7, 0xb8, 0x1e, 0x8e, 0x8d, 0x37,
	0x05, 0xaa, 0x66, 0xea, 0x05, 0xc9, 0xaf, 0x23, 0xc8, 0x11, 0xec, 0x2c, 0x30, 0x6f, 0x22, 0x12,
	0x2f, 0xd0, 0x55, 0x09, 0x15, 0xa4, 0xd6, 0x95, 0x12, 0x69, 0xc2, 0x2e, 0x67, 0x88, 0x53, 0x97,
	0xa6, 0x18, 0xbb, 0xb3, 0x98, 0x26, 0xd1, 0x54, 0xcf, 0x49, 0xae, 0x2c, 0x8d, 0x41, 0x8a, 0xf1,
	0x8d, 0x94, 0x9b, 0xe7, 0x50, 0xdc, 0xf8, 0x5f, 0x52, 0x80, 0xfc, 0x9d, 0x75, 0x6b, 0x0d, 0xc6,
	0x56, 0xe5, 0x1f, 0x29, 0x82, 0x36, 0xb0, 0x4d, 0x6b, 0xdc, 0x1d, 0x99, 0x4e, 0x45, 0x21, 0x79,
	0xc8, 0xf5, 0xae, 0xcc, 0x8a, 0xda, 0x79, 0x55, 0xa1, 0x66, 0x67, 0xd6, 0xdc, 0xd8, 0x85, 0x30,
	0xd8, 0x5b, 0x07, 0x68, 0xbc, 0xf4, 0xc9, 0xc9, 0xd6, 0xbd, 0x7f, 0x5a, 0x74, 0xdf, 0xd8, 0xc2,
	0xbf, 0x9b, 0xe0, 0xb3, 0x71, 0x71, 0xdf, 0xbf, 0x6c, 0xfc, 0x7a, 0xb1, 0xfb, 0xff, 0xf2, 0x95,
	0x9e, 0xbd, 0x07, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x43, 0x73, 0x08, 0xd9, 0x02, 0x00, 0x00,
}
