// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fetchDataService/proto/fetchDataAPI.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchDataRequestMessage struct {
	InputFile            string   `protobuf:"bytes,1,opt,name=input_file,json=inputFile,proto3" json:"input_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchDataRequestMessage) Reset()         { *m = FetchDataRequestMessage{} }
func (m *FetchDataRequestMessage) String() string { return proto.CompactTextString(m) }
func (*FetchDataRequestMessage) ProtoMessage()    {}
func (*FetchDataRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f6eee019a5b129f, []int{0}
}

func (m *FetchDataRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchDataRequestMessage.Unmarshal(m, b)
}
func (m *FetchDataRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchDataRequestMessage.Marshal(b, m, deterministic)
}
func (m *FetchDataRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchDataRequestMessage.Merge(m, src)
}
func (m *FetchDataRequestMessage) XXX_Size() int {
	return xxx_messageInfo_FetchDataRequestMessage.Size(m)
}
func (m *FetchDataRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchDataRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FetchDataRequestMessage proto.InternalMessageInfo

func (m *FetchDataRequestMessage) GetInputFile() string {
	if m != nil {
		return m.InputFile
	}
	return ""
}

type FetchDataResponseMessage struct {
	IndexNumber            []int64   `protobuf:"varint,1,rep,packed,name=index_number,json=indexNumber,proto3" json:"index_number,omitempty"`
	TimeAndDate            []float32 `protobuf:"fixed32,2,rep,packed,name=time_and_date,json=timeAndDate,proto3" json:"time_and_date,omitempty"`
	PortPropMotorCurrent   []float32 `protobuf:"fixed32,3,rep,packed,name=port_prop_motor_current,json=portPropMotorCurrent,proto3" json:"port_prop_motor_current,omitempty"`
	PortPropMotorPower     []float32 `protobuf:"fixed32,4,rep,packed,name=port_prop_motor_power,json=portPropMotorPower,proto3" json:"port_prop_motor_power,omitempty"`
	PortPropMotorSpeed     []float32 `protobuf:"fixed32,5,rep,packed,name=port_prop_motor_speed,json=portPropMotorSpeed,proto3" json:"port_prop_motor_speed,omitempty"`
	PortPropMotorVoltage   []float32 `protobuf:"fixed32,6,rep,packed,name=port_prop_motor_voltage,json=portPropMotorVoltage,proto3" json:"port_prop_motor_voltage,omitempty"`
	StbdPropMotorCurrent   []float32 `protobuf:"fixed32,7,rep,packed,name=stbd_prop_motor_current,json=stbdPropMotorCurrent,proto3" json:"stbd_prop_motor_current,omitempty"`
	StbdPropMotorPower     []float32 `protobuf:"fixed32,8,rep,packed,name=stbd_prop_motor_power,json=stbdPropMotorPower,proto3" json:"stbd_prop_motor_power,omitempty"`
	StbdPropMotorSpeed     []float32 `protobuf:"fixed32,9,rep,packed,name=stbd_prop_motor_speed,json=stbdPropMotorSpeed,proto3" json:"stbd_prop_motor_speed,omitempty"`
	StbdPropMotorVoltage   []float32 `protobuf:"fixed32,10,rep,packed,name=stbd_prop_motor_voltage,json=stbdPropMotorVoltage,proto3" json:"stbd_prop_motor_voltage,omitempty"`
	RudderOrderPort        []float32 `protobuf:"fixed32,11,rep,packed,name=rudder_order_port,json=rudderOrderPort,proto3" json:"rudder_order_port,omitempty"`
	RudderOrderStbd        []float32 `protobuf:"fixed32,12,rep,packed,name=rudder_order_stbd,json=rudderOrderStbd,proto3" json:"rudder_order_stbd,omitempty"`
	RudderPositionPort     []float32 `protobuf:"fixed32,13,rep,packed,name=rudder_position_port,json=rudderPositionPort,proto3" json:"rudder_position_port,omitempty"`
	RudderPositionStbd     []float32 `protobuf:"fixed32,14,rep,packed,name=rudder_position_stbd,json=rudderPositionStbd,proto3" json:"rudder_position_stbd,omitempty"`
	PropellerPitchPort     []float32 `protobuf:"fixed32,15,rep,packed,name=propeller_pitch_port,json=propellerPitchPort,proto3" json:"propeller_pitch_port,omitempty"`
	PropellerPitchStbd     []float32 `protobuf:"fixed32,16,rep,packed,name=propeller_pitch_stbd,json=propellerPitchStbd,proto3" json:"propeller_pitch_stbd,omitempty"`
	ShaftRpmIndicationPort []float32 `protobuf:"fixed32,17,rep,packed,name=shaft_rpm_indication_port,json=shaftRpmIndicationPort,proto3" json:"shaft_rpm_indication_port,omitempty"`
	ShaftRpmIndicationStbd []float32 `protobuf:"fixed32,18,rep,packed,name=shaft_rpm_indication_stbd,json=shaftRpmIndicationStbd,proto3" json:"shaft_rpm_indication_stbd,omitempty"`
	NavTime                []int64   `protobuf:"varint,19,rep,packed,name=nav_time,json=navTime,proto3" json:"nav_time,omitempty"`
	Latitude               []float32 `protobuf:"fixed32,20,rep,packed,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude              []float32 `protobuf:"fixed32,21,rep,packed,name=longitude,proto3" json:"longitude,omitempty"`
	Sog                    []float32 `protobuf:"fixed32,22,rep,packed,name=sog,proto3" json:"sog,omitempty"`
	Cog                    []float32 `protobuf:"fixed32,23,rep,packed,name=cog,proto3" json:"cog,omitempty"`
	Hdt                    []float32 `protobuf:"fixed32,24,rep,packed,name=hdt,proto3" json:"hdt,omitempty"`
	WindDirectionRelative  []int64   `protobuf:"varint,25,rep,packed,name=wind_direction_relative,json=windDirectionRelative,proto3" json:"wind_direction_relative,omitempty"`
	WindSpeed              []float32 `protobuf:"fixed32,26,rep,packed,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	Depth                  []float32 `protobuf:"fixed32,27,rep,packed,name=depth,proto3" json:"depth,omitempty"`
	EpochTime              []int64   `protobuf:"varint,28,rep,packed,name=epoch_time,json=epochTime,proto3" json:"epoch_time,omitempty"`
	BrashIce               []int64   `protobuf:"varint,29,rep,packed,name=brash_ice,json=brashIce,proto3" json:"brash_ice,omitempty"`
	RammingCount           []int64   `protobuf:"varint,30,rep,packed,name=ramming_count,json=rammingCount,proto3" json:"ramming_count,omitempty"`
	IceConcentration       []int64   `protobuf:"varint,31,rep,packed,name=ice_concentration,json=iceConcentration,proto3" json:"ice_concentration,omitempty"`
	IceThickness           []int64   `protobuf:"varint,32,rep,packed,name=ice_thickness,json=iceThickness,proto3" json:"ice_thickness,omitempty"`
	FlowSize               []int64   `protobuf:"varint,33,rep,packed,name=flow_size,json=flowSize,proto3" json:"flow_size,omitempty"`
	BeaufortNumber         []int64   `protobuf:"varint,34,rep,packed,name=beaufort_number,json=beaufortNumber,proto3" json:"beaufort_number,omitempty"`
	WaveDirection          []int64   `protobuf:"varint,35,rep,packed,name=wave_direction,json=waveDirection,proto3" json:"wave_direction,omitempty"`
	WaveHeightAve          []float32 `protobuf:"fixed32,36,rep,packed,name=wave_height_ave,json=waveHeightAve,proto3" json:"wave_height_ave,omitempty"`
	MaxSwellHeight         []float32 `protobuf:"fixed32,37,rep,packed,name=max_swell_height,json=maxSwellHeight,proto3" json:"max_swell_height,omitempty"`
	WaveLength             []float32 `protobuf:"fixed32,38,rep,packed,name=wave_length,json=waveLength,proto3" json:"wave_length,omitempty"`
	WavePeriodAve          []float32 `protobuf:"fixed32,39,rep,packed,name=wave_period_ave,json=wavePeriodAve,proto3" json:"wave_period_ave,omitempty"`
	EncounterFrequencyAve  []float32 `protobuf:"fixed32,40,rep,packed,name=encounter_frequency_ave,json=encounterFrequencyAve,proto3" json:"encounter_frequency_ave,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}  `json:"-"`
	XXX_unrecognized       []byte    `json:"-"`
	XXX_sizecache          int32     `json:"-"`
}

func (m *FetchDataResponseMessage) Reset()         { *m = FetchDataResponseMessage{} }
func (m *FetchDataResponseMessage) String() string { return proto.CompactTextString(m) }
func (*FetchDataResponseMessage) ProtoMessage()    {}
func (*FetchDataResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f6eee019a5b129f, []int{1}
}

func (m *FetchDataResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchDataResponseMessage.Unmarshal(m, b)
}
func (m *FetchDataResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchDataResponseMessage.Marshal(b, m, deterministic)
}
func (m *FetchDataResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchDataResponseMessage.Merge(m, src)
}
func (m *FetchDataResponseMessage) XXX_Size() int {
	return xxx_messageInfo_FetchDataResponseMessage.Size(m)
}
func (m *FetchDataResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchDataResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FetchDataResponseMessage proto.InternalMessageInfo

func (m *FetchDataResponseMessage) GetIndexNumber() []int64 {
	if m != nil {
		return m.IndexNumber
	}
	return nil
}

func (m *FetchDataResponseMessage) GetTimeAndDate() []float32 {
	if m != nil {
		return m.TimeAndDate
	}
	return nil
}

func (m *FetchDataResponseMessage) GetPortPropMotorCurrent() []float32 {
	if m != nil {
		return m.PortPropMotorCurrent
	}
	return nil
}

func (m *FetchDataResponseMessage) GetPortPropMotorPower() []float32 {
	if m != nil {
		return m.PortPropMotorPower
	}
	return nil
}

func (m *FetchDataResponseMessage) GetPortPropMotorSpeed() []float32 {
	if m != nil {
		return m.PortPropMotorSpeed
	}
	return nil
}

func (m *FetchDataResponseMessage) GetPortPropMotorVoltage() []float32 {
	if m != nil {
		return m.PortPropMotorVoltage
	}
	return nil
}

func (m *FetchDataResponseMessage) GetStbdPropMotorCurrent() []float32 {
	if m != nil {
		return m.StbdPropMotorCurrent
	}
	return nil
}

func (m *FetchDataResponseMessage) GetStbdPropMotorPower() []float32 {
	if m != nil {
		return m.StbdPropMotorPower
	}
	return nil
}

func (m *FetchDataResponseMessage) GetStbdPropMotorSpeed() []float32 {
	if m != nil {
		return m.StbdPropMotorSpeed
	}
	return nil
}

func (m *FetchDataResponseMessage) GetStbdPropMotorVoltage() []float32 {
	if m != nil {
		return m.StbdPropMotorVoltage
	}
	return nil
}

func (m *FetchDataResponseMessage) GetRudderOrderPort() []float32 {
	if m != nil {
		return m.RudderOrderPort
	}
	return nil
}

func (m *FetchDataResponseMessage) GetRudderOrderStbd() []float32 {
	if m != nil {
		return m.RudderOrderStbd
	}
	return nil
}

func (m *FetchDataResponseMessage) GetRudderPositionPort() []float32 {
	if m != nil {
		return m.RudderPositionPort
	}
	return nil
}

func (m *FetchDataResponseMessage) GetRudderPositionStbd() []float32 {
	if m != nil {
		return m.RudderPositionStbd
	}
	return nil
}

func (m *FetchDataResponseMessage) GetPropellerPitchPort() []float32 {
	if m != nil {
		return m.PropellerPitchPort
	}
	return nil
}

func (m *FetchDataResponseMessage) GetPropellerPitchStbd() []float32 {
	if m != nil {
		return m.PropellerPitchStbd
	}
	return nil
}

func (m *FetchDataResponseMessage) GetShaftRpmIndicationPort() []float32 {
	if m != nil {
		return m.ShaftRpmIndicationPort
	}
	return nil
}

func (m *FetchDataResponseMessage) GetShaftRpmIndicationStbd() []float32 {
	if m != nil {
		return m.ShaftRpmIndicationStbd
	}
	return nil
}

func (m *FetchDataResponseMessage) GetNavTime() []int64 {
	if m != nil {
		return m.NavTime
	}
	return nil
}

func (m *FetchDataResponseMessage) GetLatitude() []float32 {
	if m != nil {
		return m.Latitude
	}
	return nil
}

func (m *FetchDataResponseMessage) GetLongitude() []float32 {
	if m != nil {
		return m.Longitude
	}
	return nil
}

func (m *FetchDataResponseMessage) GetSog() []float32 {
	if m != nil {
		return m.Sog
	}
	return nil
}

func (m *FetchDataResponseMessage) GetCog() []float32 {
	if m != nil {
		return m.Cog
	}
	return nil
}

func (m *FetchDataResponseMessage) GetHdt() []float32 {
	if m != nil {
		return m.Hdt
	}
	return nil
}

func (m *FetchDataResponseMessage) GetWindDirectionRelative() []int64 {
	if m != nil {
		return m.WindDirectionRelative
	}
	return nil
}

func (m *FetchDataResponseMessage) GetWindSpeed() []float32 {
	if m != nil {
		return m.WindSpeed
	}
	return nil
}

func (m *FetchDataResponseMessage) GetDepth() []float32 {
	if m != nil {
		return m.Depth
	}
	return nil
}

func (m *FetchDataResponseMessage) GetEpochTime() []int64 {
	if m != nil {
		return m.EpochTime
	}
	return nil
}

func (m *FetchDataResponseMessage) GetBrashIce() []int64 {
	if m != nil {
		return m.BrashIce
	}
	return nil
}

func (m *FetchDataResponseMessage) GetRammingCount() []int64 {
	if m != nil {
		return m.RammingCount
	}
	return nil
}

func (m *FetchDataResponseMessage) GetIceConcentration() []int64 {
	if m != nil {
		return m.IceConcentration
	}
	return nil
}

func (m *FetchDataResponseMessage) GetIceThickness() []int64 {
	if m != nil {
		return m.IceThickness
	}
	return nil
}

func (m *FetchDataResponseMessage) GetFlowSize() []int64 {
	if m != nil {
		return m.FlowSize
	}
	return nil
}

func (m *FetchDataResponseMessage) GetBeaufortNumber() []int64 {
	if m != nil {
		return m.BeaufortNumber
	}
	return nil
}

func (m *FetchDataResponseMessage) GetWaveDirection() []int64 {
	if m != nil {
		return m.WaveDirection
	}
	return nil
}

func (m *FetchDataResponseMessage) GetWaveHeightAve() []float32 {
	if m != nil {
		return m.WaveHeightAve
	}
	return nil
}

func (m *FetchDataResponseMessage) GetMaxSwellHeight() []float32 {
	if m != nil {
		return m.MaxSwellHeight
	}
	return nil
}

func (m *FetchDataResponseMessage) GetWaveLength() []float32 {
	if m != nil {
		return m.WaveLength
	}
	return nil
}

func (m *FetchDataResponseMessage) GetWavePeriodAve() []float32 {
	if m != nil {
		return m.WavePeriodAve
	}
	return nil
}

func (m *FetchDataResponseMessage) GetEncounterFrequencyAve() []float32 {
	if m != nil {
		return m.EncounterFrequencyAve
	}
	return nil
}

func init() {
	proto.RegisterType((*FetchDataRequestMessage)(nil), "fetchData.FetchDataRequestMessage")
	proto.RegisterType((*FetchDataResponseMessage)(nil), "fetchData.FetchDataResponseMessage")
}

func init() {
	proto.RegisterFile("fetchDataService/proto/fetchDataAPI.proto", fileDescriptor_9f6eee019a5b129f)
}

var fileDescriptor_9f6eee019a5b129f = []byte{
	// 885 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x95, 0x5f, 0x53, 0x1b, 0x37,
	0x14, 0xc5, 0x87, 0xb8, 0x49, 0xb0, 0xc0, 0x60, 0x54, 0x88, 0x05, 0x49, 0x1a, 0x62, 0x9a, 0xc4,
	0x6d, 0x67, 0x70, 0xff, 0x4c, 0x33, 0xcd, 0xf4, 0x89, 0xc2, 0x30, 0x65, 0xa6, 0x69, 0x3d, 0x76,
	0xa6, 0x0f, 0xed, 0x83, 0x46, 0xd6, 0x5e, 0x7b, 0x35, 0xdd, 0x95, 0xb6, 0x92, 0xd6, 0xa6, 0xf9,
	0x08, 0xfd, 0xd4, 0x19, 0x5d, 0x79, 0x97, 0xe0, 0x2c, 0x2f, 0xc0, 0xfe, 0xce, 0x39, 0xba, 0xf7,
	0x8a, 0x5d, 0x89, 0x7c, 0x35, 0x03, 0x2f, 0xd3, 0x0b, 0xe1, 0xc5, 0x04, 0xec, 0x42, 0x49, 0x18,
	0x16, 0xd6, 0x78, 0x33, 0xac, 0xf1, 0xd9, 0xe8, 0xea, 0x14, 0x11, 0x6d, 0xd7, 0xac, 0xff, 0x13,
	0xe9, 0x5d, 0x56, 0x0f, 0x63, 0xf8, 0xb7, 0x04, 0xe7, 0xdf, 0x82, 0x73, 0x62, 0x0e, 0xf4, 0x29,
	0x21, 0x4a, 0x17, 0xa5, 0xe7, 0x33, 0x95, 0x01, 0xdb, 0x38, 0xde, 0x18, 0xb4, 0xc7, 0x6d, 0x24,
	0x97, 0x2a, 0x83, 0xfe, 0xff, 0x1d, 0xc2, 0x3e, 0x8a, 0xba, 0xc2, 0x68, 0x07, 0x55, 0xf6, 0x39,
	0xd9, 0x56, 0x3a, 0x81, 0x6b, 0xae, 0xcb, 0x7c, 0x0a, 0x96, 0x6d, 0x1c, 0xb7, 0x06, 0xad, 0xf1,
	0x16, 0xb2, 0xdf, 0x11, 0xd1, 0x3e, 0xe9, 0x78, 0x95, 0x03, 0x17, 0x3a, 0xe1, 0x89, 0xf0, 0xc0,
	0xee, 0x1d, 0xb7, 0x06, 0xf7, 0xc6, 0x5b, 0x01, 0x9e, 0xe9, 0xe4, 0x42, 0x78, 0xa0, 0x3f, 0x92,
	0x5e, 0x61, 0xac, 0xe7, 0x85, 0x35, 0x05, 0xcf, 0x8d, 0x37, 0x96, 0xcb, 0xd2, 0x5a, 0xd0, 0x9e,
	0xb5, 0xd0, 0xbd, 0x1f, 0xe4, 0x91, 0x35, 0xc5, 0xdb, 0x20, 0x9e, 0x47, 0x8d, 0x7e, 0x47, 0x0e,
	0xd6, 0x63, 0x85, 0x59, 0x82, 0x65, 0x9f, 0x61, 0x88, 0xde, 0x0a, 0x8d, 0x82, 0xd2, 0x14, 0x71,
	0x05, 0x40, 0xc2, 0xee, 0x37, 0x44, 0x26, 0x41, 0x69, 0x6a, 0x6e, 0x61, 0x32, 0x2f, 0xe6, 0xc0,
	0x1e, 0x34, 0x34, 0xf7, 0x67, 0xd4, 0x42, 0xcc, 0xf9, 0x69, 0xd2, 0x34, 0xd3, 0xc3, 0x18, 0x0b,
	0x72, 0xd3, 0x4c, 0xeb, 0xb1, 0x38, 0xd3, 0x66, 0x6c, 0xf0, 0x56, 0xa8, 0x9e, 0x69, 0x3d, 0x12,
	0x67, 0x6a, 0x37, 0x44, 0xea, 0x99, 0xd6, 0x23, 0xd5, 0x4c, 0xa4, 0xa1, 0xb9, 0x6a, 0xa6, 0xaf,
	0xc9, 0x9e, 0x2d, 0x93, 0x04, 0x2c, 0x37, 0x36, 0xfc, 0x0c, 0x83, 0xb3, 0x2d, 0x0c, 0xec, 0x46,
	0xe1, 0x8f, 0xc0, 0x47, 0xc6, 0xfa, 0x4f, 0xbc, 0x61, 0x41, 0xb6, 0xfd, 0x89, 0x77, 0xe2, 0xa7,
	0x09, 0xfd, 0x96, 0xec, 0xaf, 0xbc, 0x85, 0x71, 0xca, 0x2b, 0xa3, 0xe3, 0xd2, 0x9d, 0x38, 0x40,
	0xd4, 0x46, 0x2b, 0x09, 0x57, 0x6f, 0x48, 0x60, 0x81, 0x9d, 0xa6, 0x44, 0x55, 0x23, 0x4c, 0x0b,
	0x59, 0x16, 0x42, 0xca, 0xcb, 0x34, 0xd6, 0xd8, 0x5d, 0xfd, 0xe3, 0x2b, 0x6d, 0x14, 0xa4, 0xaa,
	0xc6, 0x7a, 0x02, 0x6b, 0x74, 0x9b, 0x12, 0x58, 0xe3, 0x0d, 0x39, 0x74, 0xa9, 0x98, 0x79, 0x6e,
	0x8b, 0x9c, 0x2b, 0x9d, 0x28, 0x29, 0x6e, 0x86, 0xd9, 0xc3, 0xd8, 0x23, 0x34, 0x8c, 0x8b, 0xfc,
	0xaa, 0x96, 0xb1, 0xd8, 0x5d, 0x51, 0xac, 0x48, 0xef, 0x8a, 0x62, 0xd5, 0x43, 0xb2, 0xa9, 0xc5,
	0x82, 0x87, 0x0f, 0x8a, 0x7d, 0x8e, 0x1f, 0xe0, 0x43, 0x2d, 0x16, 0xef, 0x54, 0x0e, 0xf4, 0x88,
	0x6c, 0x66, 0xc2, 0x2b, 0x5f, 0x26, 0xc0, 0xf6, 0x71, 0x91, 0xfa, 0x99, 0x3e, 0x21, 0xed, 0xcc,
	0xe8, 0x79, 0x14, 0x0f, 0x50, 0xbc, 0x01, 0xb4, 0x4b, 0x5a, 0xce, 0xcc, 0xd9, 0x23, 0xe4, 0xe1,
	0xcf, 0x40, 0xa4, 0x99, 0xb3, 0x5e, 0x24, 0x32, 0x92, 0x34, 0xf1, 0x8c, 0x45, 0x92, 0x26, 0x9e,
	0xbe, 0x26, 0xbd, 0xa5, 0x0a, 0x1f, 0xba, 0xb2, 0x20, 0xb1, 0x7f, 0x0b, 0xa1, 0xe0, 0x02, 0xd8,
	0x21, 0x76, 0x76, 0x10, 0xe4, 0x8b, 0x4a, 0x1d, 0xaf, 0xc4, 0x70, 0x06, 0x61, 0x2e, 0xbe, 0xb7,
	0x47, 0xb1, 0x99, 0x40, 0xe2, 0xeb, 0xba, 0x4f, 0xee, 0x27, 0x50, 0xf8, 0x94, 0x3d, 0x46, 0x25,
	0x3e, 0x84, 0x10, 0x14, 0x46, 0xa6, 0x71, 0xf2, 0x27, 0xb8, 0x7e, 0x1b, 0x09, 0xce, 0xfe, 0x98,
	0xb4, 0xa7, 0x56, 0xb8, 0x94, 0x2b, 0x09, 0xec, 0x29, 0xaa, 0x9b, 0x08, 0xae, 0x24, 0xd0, 0x13,
	0xd2, 0xb1, 0x22, 0xcf, 0x95, 0x9e, 0x73, 0x69, 0x4a, 0xed, 0xd9, 0x17, 0x68, 0xd8, 0x5e, 0xc1,
	0xf3, 0xc0, 0xe8, 0x37, 0x64, 0x4f, 0x49, 0xe0, 0xd2, 0x68, 0x09, 0xda, 0x5b, 0xdc, 0x71, 0xf6,
	0x0c, 0x8d, 0x5d, 0x25, 0xe1, 0xfc, 0x63, 0x1e, 0x56, 0x0c, 0x66, 0x9f, 0x2a, 0xf9, 0x8f, 0x06,
	0xe7, 0xd8, 0x71, 0x5c, 0x51, 0x49, 0x78, 0x57, 0xb1, 0xd0, 0xd3, 0x2c, 0x33, 0x4b, 0xee, 0xd4,
	0x7b, 0x60, 0xcf, 0x63, 0x4f, 0x01, 0x4c, 0xd4, 0x7b, 0xa0, 0xaf, 0xc8, 0xee, 0x14, 0x44, 0x39,
	0x0b, 0x87, 0xcd, 0xea, 0x3c, 0xed, 0xa3, 0x65, 0xa7, 0xc2, 0xab, 0x23, 0xf5, 0x05, 0xd9, 0x59,
	0x8a, 0x05, 0xdc, 0xec, 0x32, 0x3b, 0x41, 0x5f, 0x27, 0xd0, 0x7a, 0x73, 0xe9, 0x4b, 0xb2, 0x8b,
	0xb6, 0x14, 0xd4, 0x3c, 0xf5, 0x5c, 0x2c, 0x80, 0x7d, 0x89, 0xfb, 0x87, 0xbe, 0x5f, 0x91, 0x9e,
	0x2d, 0x80, 0x0e, 0x48, 0x37, 0x17, 0xd7, 0xdc, 0x2d, 0x21, 0xcb, 0x56, 0x66, 0xf6, 0x02, 0x8d,
	0x3b, 0xb9, 0xb8, 0x9e, 0x04, 0x1c, 0xcd, 0xf4, 0x19, 0xd9, 0xc2, 0x15, 0x33, 0xd0, 0x73, 0x9f,
	0xb2, 0x97, 0x68, 0x22, 0x01, 0xfd, 0x86, 0xa4, 0x2e, 0x59, 0x80, 0x55, 0x26, 0xc1, 0x92, 0xaf,
	0x6e, 0x4a, 0x8e, 0x90, 0x86, 0x92, 0xaf, 0x49, 0x0f, 0x34, 0x6e, 0x3c, 0x58, 0x3e, 0xb3, 0xe1,
	0x42, 0xd2, 0xf2, 0x3f, 0xf4, 0x0f, 0xd0, 0x7f, 0x50, 0xcb, 0x97, 0x95, 0x7a, 0xb6, 0x80, 0xef,
	0x53, 0xd2, 0xae, 0xef, 0x22, 0xfa, 0x37, 0xe9, 0x5e, 0xae, 0xdd, 0x85, 0xb4, 0x7f, 0x5a, 0xdf,
	0x79, 0xa7, 0x77, 0x5c, 0x78, 0x47, 0x27, 0xcd, 0x9e, 0x5b, 0x37, 0xdb, 0x2f, 0x3f, 0xff, 0xf5,
	0x66, 0xae, 0x7c, 0x5a, 0x4e, 0x4f, 0xa5, 0xc9, 0x87, 0x5a, 0xc9, 0xd4, 0x64, 0xc2, 0x4d, 0x4b,
	0xad, 0x87, 0xb9, 0x70, 0x1e, 0xac, 0x1b, 0x3a, 0x2b, 0x87, 0xe0, 0xbc, 0xca, 0x85, 0x87, 0x5b,
	0x77, 0xf1, 0xf4, 0x01, 0xfe, 0xfa, 0xe1, 0x43, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x09, 0x1f,
	0x4b, 0xac, 0x07, 0x00, 0x00,
}
