# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.prepareDataAPI_pb2 as prepareDataAPI__pb2


class PrepareDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareEstimateDataService = channel.unary_unary(
                '/prepareData.PrepareData/PrepareEstimateDataService',
                request_serializer=prepareDataAPI__pb2.PrepareRequestMessage.SerializeToString,
                response_deserializer=prepareDataAPI__pb2.PrepareResponseMessage.FromString,
                )


class PrepareDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PrepareEstimateDataService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrepareDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareEstimateDataService': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareEstimateDataService,
                    request_deserializer=prepareDataAPI__pb2.PrepareRequestMessage.FromString,
                    response_serializer=prepareDataAPI__pb2.PrepareResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prepareData.PrepareData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PrepareData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrepareEstimateDataService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/prepareData.PrepareData/PrepareEstimateDataService',
            prepareDataAPI__pb2.PrepareRequestMessage.SerializeToString,
            prepareDataAPI__pb2.PrepareResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
