// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prepareDataService/proto/prepareDataAPI.proto

package prepareData

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrepareRequestMessage struct {
	IndexNumber            []int64   `protobuf:"varint,1,rep,packed,name=index_number,json=indexNumber,proto3" json:"index_number,omitempty"`
	TimeAndDate            []float32 `protobuf:"fixed32,2,rep,packed,name=time_and_date,json=timeAndDate,proto3" json:"time_and_date,omitempty"`
	PortPropMotorCurrent   []float32 `protobuf:"fixed32,3,rep,packed,name=port_prop_motor_current,json=portPropMotorCurrent,proto3" json:"port_prop_motor_current,omitempty"`
	PortPropMotorPower     []float32 `protobuf:"fixed32,4,rep,packed,name=port_prop_motor_power,json=portPropMotorPower,proto3" json:"port_prop_motor_power,omitempty"`
	PortPropMotorSpeed     []float32 `protobuf:"fixed32,5,rep,packed,name=port_prop_motor_speed,json=portPropMotorSpeed,proto3" json:"port_prop_motor_speed,omitempty"`
	PortPropMotorVoltage   []float32 `protobuf:"fixed32,6,rep,packed,name=port_prop_motor_voltage,json=portPropMotorVoltage,proto3" json:"port_prop_motor_voltage,omitempty"`
	StbdPropMotorCurrent   []float32 `protobuf:"fixed32,7,rep,packed,name=stbd_prop_motor_current,json=stbdPropMotorCurrent,proto3" json:"stbd_prop_motor_current,omitempty"`
	StbdPropMotorPower     []float32 `protobuf:"fixed32,8,rep,packed,name=stbd_prop_motor_power,json=stbdPropMotorPower,proto3" json:"stbd_prop_motor_power,omitempty"`
	StbdPropMotorSpeed     []float32 `protobuf:"fixed32,9,rep,packed,name=stbd_prop_motor_speed,json=stbdPropMotorSpeed,proto3" json:"stbd_prop_motor_speed,omitempty"`
	StbdPropMotorVoltage   []float32 `protobuf:"fixed32,10,rep,packed,name=stbd_prop_motor_voltage,json=stbdPropMotorVoltage,proto3" json:"stbd_prop_motor_voltage,omitempty"`
	RudderOrderPort        []float32 `protobuf:"fixed32,11,rep,packed,name=rudder_order_port,json=rudderOrderPort,proto3" json:"rudder_order_port,omitempty"`
	RudderOrderStbd        []float32 `protobuf:"fixed32,12,rep,packed,name=rudder_order_stbd,json=rudderOrderStbd,proto3" json:"rudder_order_stbd,omitempty"`
	RudderPositionPort     []float32 `protobuf:"fixed32,13,rep,packed,name=rudder_position_port,json=rudderPositionPort,proto3" json:"rudder_position_port,omitempty"`
	RudderPositionStbd     []float32 `protobuf:"fixed32,14,rep,packed,name=rudder_position_stbd,json=rudderPositionStbd,proto3" json:"rudder_position_stbd,omitempty"`
	PropellerPitchPort     []float32 `protobuf:"fixed32,15,rep,packed,name=propeller_pitch_port,json=propellerPitchPort,proto3" json:"propeller_pitch_port,omitempty"`
	PropellerPitchStbd     []float32 `protobuf:"fixed32,16,rep,packed,name=propeller_pitch_stbd,json=propellerPitchStbd,proto3" json:"propeller_pitch_stbd,omitempty"`
	ShaftRpmIndicationPort []float32 `protobuf:"fixed32,17,rep,packed,name=shaft_rpm_indication_port,json=shaftRpmIndicationPort,proto3" json:"shaft_rpm_indication_port,omitempty"`
	ShaftRpmIndicationStbd []float32 `protobuf:"fixed32,18,rep,packed,name=shaft_rpm_indication_stbd,json=shaftRpmIndicationStbd,proto3" json:"shaft_rpm_indication_stbd,omitempty"`
	NavTime                []int64   `protobuf:"varint,19,rep,packed,name=nav_time,json=navTime,proto3" json:"nav_time,omitempty"`
	Latitude               []float32 `protobuf:"fixed32,20,rep,packed,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude              []float32 `protobuf:"fixed32,21,rep,packed,name=longitude,proto3" json:"longitude,omitempty"`
	Sog                    []float32 `protobuf:"fixed32,22,rep,packed,name=sog,proto3" json:"sog,omitempty"`
	Cog                    []float32 `protobuf:"fixed32,23,rep,packed,name=cog,proto3" json:"cog,omitempty"`
	Hdt                    []float32 `protobuf:"fixed32,24,rep,packed,name=hdt,proto3" json:"hdt,omitempty"`
	WindDirectionRelative  []int64   `protobuf:"varint,25,rep,packed,name=wind_direction_relative,json=windDirectionRelative,proto3" json:"wind_direction_relative,omitempty"`
	WindSpeed              []float32 `protobuf:"fixed32,26,rep,packed,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	Depth                  []float32 `protobuf:"fixed32,27,rep,packed,name=depth,proto3" json:"depth,omitempty"`
	EpochTime              []int64   `protobuf:"varint,28,rep,packed,name=epoch_time,json=epochTime,proto3" json:"epoch_time,omitempty"`
	BrashIce               []int64   `protobuf:"varint,29,rep,packed,name=brash_ice,json=brashIce,proto3" json:"brash_ice,omitempty"`
	RammingCount           []int64   `protobuf:"varint,30,rep,packed,name=ramming_count,json=rammingCount,proto3" json:"ramming_count,omitempty"`
	IceConcentration       []int64   `protobuf:"varint,31,rep,packed,name=ice_concentration,json=iceConcentration,proto3" json:"ice_concentration,omitempty"`
	IceThickness           []int64   `protobuf:"varint,32,rep,packed,name=ice_thickness,json=iceThickness,proto3" json:"ice_thickness,omitempty"`
	FlowSize               []int64   `protobuf:"varint,33,rep,packed,name=flow_size,json=flowSize,proto3" json:"flow_size,omitempty"`
	BeaufortNumber         []int64   `protobuf:"varint,34,rep,packed,name=beaufort_number,json=beaufortNumber,proto3" json:"beaufort_number,omitempty"`
	WaveDirection          []int64   `protobuf:"varint,35,rep,packed,name=wave_direction,json=waveDirection,proto3" json:"wave_direction,omitempty"`
	WaveHeightAve          []float32 `protobuf:"fixed32,36,rep,packed,name=wave_height_ave,json=waveHeightAve,proto3" json:"wave_height_ave,omitempty"`
	MaxSwellHeight         []float32 `protobuf:"fixed32,37,rep,packed,name=max_swell_height,json=maxSwellHeight,proto3" json:"max_swell_height,omitempty"`
	WaveLength             []float32 `protobuf:"fixed32,38,rep,packed,name=wave_length,json=waveLength,proto3" json:"wave_length,omitempty"`
	WavePeriodAve          []float32 `protobuf:"fixed32,39,rep,packed,name=wave_period_ave,json=wavePeriodAve,proto3" json:"wave_period_ave,omitempty"`
	EncounterFrequencyAve  []float32 `protobuf:"fixed32,40,rep,packed,name=encounter_frequency_ave,json=encounterFrequencyAve,proto3" json:"encounter_frequency_ave,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}  `json:"-"`
	XXX_unrecognized       []byte    `json:"-"`
	XXX_sizecache          int32     `json:"-"`
}

func (m *PrepareRequestMessage) Reset()         { *m = PrepareRequestMessage{} }
func (m *PrepareRequestMessage) String() string { return proto.CompactTextString(m) }
func (*PrepareRequestMessage) ProtoMessage()    {}
func (*PrepareRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b149cda5db2609, []int{0}
}

func (m *PrepareRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareRequestMessage.Unmarshal(m, b)
}
func (m *PrepareRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareRequestMessage.Marshal(b, m, deterministic)
}
func (m *PrepareRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareRequestMessage.Merge(m, src)
}
func (m *PrepareRequestMessage) XXX_Size() int {
	return xxx_messageInfo_PrepareRequestMessage.Size(m)
}
func (m *PrepareRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareRequestMessage proto.InternalMessageInfo

func (m *PrepareRequestMessage) GetIndexNumber() []int64 {
	if m != nil {
		return m.IndexNumber
	}
	return nil
}

func (m *PrepareRequestMessage) GetTimeAndDate() []float32 {
	if m != nil {
		return m.TimeAndDate
	}
	return nil
}

func (m *PrepareRequestMessage) GetPortPropMotorCurrent() []float32 {
	if m != nil {
		return m.PortPropMotorCurrent
	}
	return nil
}

func (m *PrepareRequestMessage) GetPortPropMotorPower() []float32 {
	if m != nil {
		return m.PortPropMotorPower
	}
	return nil
}

func (m *PrepareRequestMessage) GetPortPropMotorSpeed() []float32 {
	if m != nil {
		return m.PortPropMotorSpeed
	}
	return nil
}

func (m *PrepareRequestMessage) GetPortPropMotorVoltage() []float32 {
	if m != nil {
		return m.PortPropMotorVoltage
	}
	return nil
}

func (m *PrepareRequestMessage) GetStbdPropMotorCurrent() []float32 {
	if m != nil {
		return m.StbdPropMotorCurrent
	}
	return nil
}

func (m *PrepareRequestMessage) GetStbdPropMotorPower() []float32 {
	if m != nil {
		return m.StbdPropMotorPower
	}
	return nil
}

func (m *PrepareRequestMessage) GetStbdPropMotorSpeed() []float32 {
	if m != nil {
		return m.StbdPropMotorSpeed
	}
	return nil
}

func (m *PrepareRequestMessage) GetStbdPropMotorVoltage() []float32 {
	if m != nil {
		return m.StbdPropMotorVoltage
	}
	return nil
}

func (m *PrepareRequestMessage) GetRudderOrderPort() []float32 {
	if m != nil {
		return m.RudderOrderPort
	}
	return nil
}

func (m *PrepareRequestMessage) GetRudderOrderStbd() []float32 {
	if m != nil {
		return m.RudderOrderStbd
	}
	return nil
}

func (m *PrepareRequestMessage) GetRudderPositionPort() []float32 {
	if m != nil {
		return m.RudderPositionPort
	}
	return nil
}

func (m *PrepareRequestMessage) GetRudderPositionStbd() []float32 {
	if m != nil {
		return m.RudderPositionStbd
	}
	return nil
}

func (m *PrepareRequestMessage) GetPropellerPitchPort() []float32 {
	if m != nil {
		return m.PropellerPitchPort
	}
	return nil
}

func (m *PrepareRequestMessage) GetPropellerPitchStbd() []float32 {
	if m != nil {
		return m.PropellerPitchStbd
	}
	return nil
}

func (m *PrepareRequestMessage) GetShaftRpmIndicationPort() []float32 {
	if m != nil {
		return m.ShaftRpmIndicationPort
	}
	return nil
}

func (m *PrepareRequestMessage) GetShaftRpmIndicationStbd() []float32 {
	if m != nil {
		return m.ShaftRpmIndicationStbd
	}
	return nil
}

func (m *PrepareRequestMessage) GetNavTime() []int64 {
	if m != nil {
		return m.NavTime
	}
	return nil
}

func (m *PrepareRequestMessage) GetLatitude() []float32 {
	if m != nil {
		return m.Latitude
	}
	return nil
}

func (m *PrepareRequestMessage) GetLongitude() []float32 {
	if m != nil {
		return m.Longitude
	}
	return nil
}

func (m *PrepareRequestMessage) GetSog() []float32 {
	if m != nil {
		return m.Sog
	}
	return nil
}

func (m *PrepareRequestMessage) GetCog() []float32 {
	if m != nil {
		return m.Cog
	}
	return nil
}

func (m *PrepareRequestMessage) GetHdt() []float32 {
	if m != nil {
		return m.Hdt
	}
	return nil
}

func (m *PrepareRequestMessage) GetWindDirectionRelative() []int64 {
	if m != nil {
		return m.WindDirectionRelative
	}
	return nil
}

func (m *PrepareRequestMessage) GetWindSpeed() []float32 {
	if m != nil {
		return m.WindSpeed
	}
	return nil
}

func (m *PrepareRequestMessage) GetDepth() []float32 {
	if m != nil {
		return m.Depth
	}
	return nil
}

func (m *PrepareRequestMessage) GetEpochTime() []int64 {
	if m != nil {
		return m.EpochTime
	}
	return nil
}

func (m *PrepareRequestMessage) GetBrashIce() []int64 {
	if m != nil {
		return m.BrashIce
	}
	return nil
}

func (m *PrepareRequestMessage) GetRammingCount() []int64 {
	if m != nil {
		return m.RammingCount
	}
	return nil
}

func (m *PrepareRequestMessage) GetIceConcentration() []int64 {
	if m != nil {
		return m.IceConcentration
	}
	return nil
}

func (m *PrepareRequestMessage) GetIceThickness() []int64 {
	if m != nil {
		return m.IceThickness
	}
	return nil
}

func (m *PrepareRequestMessage) GetFlowSize() []int64 {
	if m != nil {
		return m.FlowSize
	}
	return nil
}

func (m *PrepareRequestMessage) GetBeaufortNumber() []int64 {
	if m != nil {
		return m.BeaufortNumber
	}
	return nil
}

func (m *PrepareRequestMessage) GetWaveDirection() []int64 {
	if m != nil {
		return m.WaveDirection
	}
	return nil
}

func (m *PrepareRequestMessage) GetWaveHeightAve() []float32 {
	if m != nil {
		return m.WaveHeightAve
	}
	return nil
}

func (m *PrepareRequestMessage) GetMaxSwellHeight() []float32 {
	if m != nil {
		return m.MaxSwellHeight
	}
	return nil
}

func (m *PrepareRequestMessage) GetWaveLength() []float32 {
	if m != nil {
		return m.WaveLength
	}
	return nil
}

func (m *PrepareRequestMessage) GetWavePeriodAve() []float32 {
	if m != nil {
		return m.WavePeriodAve
	}
	return nil
}

func (m *PrepareRequestMessage) GetEncounterFrequencyAve() []float32 {
	if m != nil {
		return m.EncounterFrequencyAve
	}
	return nil
}

type PrepareResponseMessage struct {
	PortPropMotorSpeed    []float32 `protobuf:"fixed32,1,rep,packed,name=port_prop_motor_speed,json=portPropMotorSpeed,proto3" json:"port_prop_motor_speed,omitempty"`
	StbdPropMotorSpeed    []float32 `protobuf:"fixed32,2,rep,packed,name=stbd_prop_motor_speed,json=stbdPropMotorSpeed,proto3" json:"stbd_prop_motor_speed,omitempty"`
	PropellerPitchPort    []float32 `protobuf:"fixed32,3,rep,packed,name=propeller_pitch_port,json=propellerPitchPort,proto3" json:"propeller_pitch_port,omitempty"`
	PropellerPitchStbd    []float32 `protobuf:"fixed32,4,rep,packed,name=propeller_pitch_stbd,json=propellerPitchStbd,proto3" json:"propeller_pitch_stbd,omitempty"`
	Sog                   []float32 `protobuf:"fixed32,5,rep,packed,name=sog,proto3" json:"sog,omitempty"`
	WindDirectionRelative []float32 `protobuf:"fixed32,6,rep,packed,name=wind_direction_relative,json=windDirectionRelative,proto3" json:"wind_direction_relative,omitempty"`
	WindSpeed             []float32 `protobuf:"fixed32,7,rep,packed,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	BeaufortNumber        []float32 `protobuf:"fixed32,8,rep,packed,name=beaufort_number,json=beaufortNumber,proto3" json:"beaufort_number,omitempty"`
	WaveDirection         []float32 `protobuf:"fixed32,9,rep,packed,name=wave_direction,json=waveDirection,proto3" json:"wave_direction,omitempty"`
	WaveLength            []float32 `protobuf:"fixed32,10,rep,packed,name=wave_length,json=waveLength,proto3" json:"wave_length,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}  `json:"-"`
	XXX_unrecognized      []byte    `json:"-"`
	XXX_sizecache         int32     `json:"-"`
}

func (m *PrepareResponseMessage) Reset()         { *m = PrepareResponseMessage{} }
func (m *PrepareResponseMessage) String() string { return proto.CompactTextString(m) }
func (*PrepareResponseMessage) ProtoMessage()    {}
func (*PrepareResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b149cda5db2609, []int{1}
}

func (m *PrepareResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareResponseMessage.Unmarshal(m, b)
}
func (m *PrepareResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareResponseMessage.Marshal(b, m, deterministic)
}
func (m *PrepareResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareResponseMessage.Merge(m, src)
}
func (m *PrepareResponseMessage) XXX_Size() int {
	return xxx_messageInfo_PrepareResponseMessage.Size(m)
}
func (m *PrepareResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareResponseMessage proto.InternalMessageInfo

func (m *PrepareResponseMessage) GetPortPropMotorSpeed() []float32 {
	if m != nil {
		return m.PortPropMotorSpeed
	}
	return nil
}

func (m *PrepareResponseMessage) GetStbdPropMotorSpeed() []float32 {
	if m != nil {
		return m.StbdPropMotorSpeed
	}
	return nil
}

func (m *PrepareResponseMessage) GetPropellerPitchPort() []float32 {
	if m != nil {
		return m.PropellerPitchPort
	}
	return nil
}

func (m *PrepareResponseMessage) GetPropellerPitchStbd() []float32 {
	if m != nil {
		return m.PropellerPitchStbd
	}
	return nil
}

func (m *PrepareResponseMessage) GetSog() []float32 {
	if m != nil {
		return m.Sog
	}
	return nil
}

func (m *PrepareResponseMessage) GetWindDirectionRelative() []float32 {
	if m != nil {
		return m.WindDirectionRelative
	}
	return nil
}

func (m *PrepareResponseMessage) GetWindSpeed() []float32 {
	if m != nil {
		return m.WindSpeed
	}
	return nil
}

func (m *PrepareResponseMessage) GetBeaufortNumber() []float32 {
	if m != nil {
		return m.BeaufortNumber
	}
	return nil
}

func (m *PrepareResponseMessage) GetWaveDirection() []float32 {
	if m != nil {
		return m.WaveDirection
	}
	return nil
}

func (m *PrepareResponseMessage) GetWaveLength() []float32 {
	if m != nil {
		return m.WaveLength
	}
	return nil
}

func init() {
	proto.RegisterType((*PrepareRequestMessage)(nil), "prepareData.PrepareRequestMessage")
	proto.RegisterType((*PrepareResponseMessage)(nil), "prepareData.PrepareResponseMessage")
}

func init() {
	proto.RegisterFile("prepareDataService/proto/prepareDataAPI.proto", fileDescriptor_46b149cda5db2609)
}

var fileDescriptor_46b149cda5db2609 = []byte{
	// 901 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x6d, 0x6f, 0xdb, 0x36,
	0x10, 0x46, 0xe3, 0xa6, 0x89, 0xe9, 0x38, 0x2f, 0x5c, 0x9c, 0x30, 0x69, 0xbb, 0xa6, 0xce, 0xda,
	0x06, 0x1b, 0x96, 0xee, 0x05, 0x2b, 0xb0, 0x8f, 0x41, 0xb2, 0x61, 0x01, 0xd6, 0x4d, 0xb0, 0x8b,
	0x7d, 0x25, 0x68, 0xea, 0x6c, 0x11, 0x93, 0x48, 0x8d, 0xa2, 0xe5, 0xac, 0x7f, 0x60, 0x7f, 0x6a,
	0x3f, 0x6e, 0xe0, 0x51, 0xb2, 0x1d, 0x57, 0xde, 0xd6, 0x2f, 0x41, 0xf4, 0xbc, 0xf0, 0xee, 0x68,
	0xde, 0x91, 0xe4, 0xcb, 0xdc, 0x42, 0x2e, 0x2c, 0xdc, 0x08, 0x27, 0x86, 0x60, 0x4b, 0x25, 0xe1,
	0x75, 0x6e, 0x8d, 0x33, 0xaf, 0x97, 0x88, 0xab, 0xe8, 0xf6, 0x12, 0x41, 0xda, 0x59, 0x42, 0xfb,
	0x7f, 0x75, 0x49, 0x2f, 0x0a, 0xdf, 0x03, 0xf8, 0x63, 0x0a, 0x85, 0x7b, 0x0b, 0x45, 0x21, 0x26,
	0x40, 0x9f, 0x93, 0x1d, 0xa5, 0x63, 0xb8, 0xe3, 0x7a, 0x9a, 0x8d, 0xc0, 0xb2, 0x07, 0x67, 0xad,
	0x8b, 0xd6, 0xa0, 0x83, 0xd8, 0x2f, 0x08, 0xd1, 0x3e, 0xe9, 0x3a, 0x95, 0x01, 0x17, 0x3a, 0xe6,
	0xb1, 0x70, 0xc0, 0x36, 0xce, 0x5a, 0x17, 0x1b, 0x83, 0x8e, 0x07, 0xaf, 0x74, 0x7c, 0x23, 0x1c,
	0xd0, 0xef, 0xc8, 0x71, 0x6e, 0xac, 0xe3, 0xb9, 0x35, 0x39, 0xcf, 0x8c, 0x33, 0x96, 0xcb, 0xa9,
	0xb5, 0xa0, 0x1d, 0x6b, 0xa1, 0xfa, 0xd0, 0xd3, 0x91, 0x35, 0xf9, 0x5b, 0x4f, 0x5e, 0x07, 0x8e,
	0x7e, 0x4d, 0x7a, 0xab, 0xb6, 0xdc, 0xcc, 0xc0, 0xb2, 0x87, 0x68, 0xa2, 0xf7, 0x4c, 0x91, 0x67,
	0x9a, 0x2c, 0x45, 0x0e, 0x10, 0xb3, 0xcd, 0x06, 0xcb, 0xd0, 0x33, 0x4d, 0xc9, 0x95, 0x26, 0x75,
	0x62, 0x02, 0xec, 0x51, 0x43, 0x72, 0xbf, 0x05, 0xce, 0xdb, 0x0a, 0x37, 0x8a, 0x9b, 0x6a, 0xda,
	0x0a, 0x36, 0x4f, 0x37, 0xd5, 0xb4, 0x6a, 0x0b, 0x35, 0x6d, 0x87, 0x04, 0xef, 0x99, 0xe6, 0x35,
	0xad, 0x5a, 0x42, 0x4d, 0xed, 0x06, 0xcb, 0xbc, 0xa6, 0x55, 0x4b, 0x5d, 0x13, 0x69, 0x48, 0xae,
	0xae, 0xe9, 0x73, 0x72, 0x60, 0xa7, 0x71, 0x0c, 0x96, 0x1b, 0xeb, 0xff, 0xfa, 0xc2, 0x59, 0x07,
	0x0d, 0x7b, 0x81, 0xf8, 0xd5, 0xe3, 0x91, 0xb1, 0xee, 0x03, 0xad, 0x5f, 0x90, 0xed, 0x7c, 0xa0,
	0x1d, 0xba, 0x51, 0x4c, 0xbf, 0x22, 0x87, 0x95, 0x36, 0x37, 0x85, 0x72, 0xca, 0xe8, 0xb0, 0x74,
	0x37, 0x14, 0x10, 0xb8, 0xa8, 0xa2, 0x70, 0xf5, 0x06, 0x07, 0x06, 0xd8, 0x6d, 0x72, 0xd4, 0x31,
	0x7c, 0xb5, 0x90, 0xa6, 0xde, 0xa4, 0x9c, 0x4c, 0x42, 0x8c, 0xbd, 0xea, 0x87, 0xaf, 0xb9, 0xc8,
	0x53, 0x75, 0x8c, 0x55, 0x07, 0xc6, 0xd8, 0x6f, 0x72, 0x60, 0x8c, 0xef, 0xc9, 0x49, 0x91, 0x88,
	0xb1, 0xe3, 0x36, 0xcf, 0xb8, 0xd2, 0xb1, 0x92, 0x62, 0x51, 0xcc, 0x01, 0xda, 0x8e, 0x50, 0x30,
	0xc8, 0xb3, 0xdb, 0x39, 0x8d, 0xc1, 0xd6, 0x59, 0x31, 0x22, 0x5d, 0x67, 0xc5, 0xa8, 0x27, 0x64,
	0x5b, 0x8b, 0x92, 0xfb, 0x86, 0x62, 0x9f, 0x60, 0x03, 0x6e, 0x69, 0x51, 0xbe, 0x53, 0x19, 0xd0,
	0x53, 0xb2, 0x9d, 0x0a, 0xa7, 0xdc, 0x34, 0x06, 0x76, 0x88, 0x8b, 0xcc, 0xbf, 0xe9, 0x13, 0xd2,
	0x4e, 0x8d, 0x9e, 0x04, 0xb2, 0x87, 0xe4, 0x02, 0xa0, 0xfb, 0xa4, 0x55, 0x98, 0x09, 0x3b, 0x42,
	0xdc, 0xff, 0xeb, 0x11, 0x69, 0x26, 0xec, 0x38, 0x20, 0x32, 0x20, 0x49, 0xec, 0x18, 0x0b, 0x48,
	0x12, 0x3b, 0xfa, 0x86, 0x1c, 0xcf, 0x94, 0x6f, 0x74, 0x65, 0x41, 0x62, 0xfe, 0x16, 0x7c, 0xc0,
	0x12, 0xd8, 0x09, 0x66, 0xd6, 0xf3, 0xf4, 0x4d, 0xcd, 0x0e, 0x2a, 0x92, 0x3e, 0x25, 0x04, 0x7d,
	0xe1, 0xdc, 0x9e, 0x86, 0x64, 0x3c, 0x12, 0x8e, 0xeb, 0x21, 0xd9, 0x8c, 0x21, 0x77, 0x09, 0x7b,
	0x8c, 0x4c, 0xf8, 0xf0, 0x26, 0xc8, 0x8d, 0x4c, 0x42, 0xe5, 0x4f, 0x70, 0xfd, 0x36, 0x22, 0x58,
	0xfb, 0x63, 0xd2, 0x1e, 0x59, 0x51, 0x24, 0x5c, 0x49, 0x60, 0x4f, 0x91, 0xdd, 0x46, 0xe0, 0x56,
	0x02, 0x3d, 0x27, 0x5d, 0x2b, 0xb2, 0x4c, 0xe9, 0x09, 0x97, 0x66, 0xaa, 0x1d, 0xfb, 0x14, 0x05,
	0x3b, 0x15, 0x78, 0xed, 0x31, 0xfa, 0x05, 0x39, 0x50, 0x12, 0xb8, 0x34, 0x5a, 0x82, 0x76, 0x16,
	0x77, 0x9c, 0x3d, 0x43, 0xe1, 0xbe, 0x92, 0x70, 0xbd, 0x8c, 0xfb, 0x15, 0xbd, 0xd8, 0x25, 0x4a,
	0xfe, 0xae, 0xa1, 0x28, 0xd8, 0x59, 0x58, 0x51, 0x49, 0x78, 0x57, 0x63, 0x3e, 0xa7, 0x71, 0x6a,
	0x66, 0xbc, 0x50, 0xef, 0x81, 0x3d, 0x0f, 0x39, 0x79, 0x60, 0xa8, 0xde, 0x03, 0x7d, 0x45, 0xf6,
	0x46, 0x20, 0xa6, 0x63, 0x3f, 0x6c, 0xaa, 0x79, 0xda, 0x47, 0xc9, 0x6e, 0x0d, 0x57, 0x23, 0xf5,
	0x05, 0xd9, 0x9d, 0x89, 0x12, 0x16, 0xbb, 0xcc, 0xce, 0x51, 0xd7, 0xf5, 0xe8, 0x7c, 0x73, 0xe9,
	0x4b, 0xb2, 0x87, 0xb2, 0x04, 0xd4, 0x24, 0x71, 0x5c, 0x94, 0xc0, 0x3e, 0xc3, 0xfd, 0x43, 0xdd,
	0x4f, 0x88, 0x5e, 0x95, 0x40, 0x2f, 0xc8, 0x7e, 0x26, 0xee, 0x78, 0x31, 0x83, 0x34, 0xad, 0xc4,
	0xec, 0x05, 0x0a, 0x77, 0x33, 0x71, 0x37, 0xf4, 0x70, 0x10, 0xd3, 0x67, 0xa4, 0x83, 0x2b, 0xa6,
	0xa0, 0x27, 0x2e, 0x61, 0x2f, 0x51, 0x44, 0x3c, 0xf4, 0x33, 0x22, 0xf3, 0x90, 0x39, 0x58, 0x65,
	0x62, 0x0c, 0xf9, 0x6a, 0x11, 0x32, 0x42, 0xd4, 0x87, 0x7c, 0x43, 0x8e, 0x41, 0xe3, 0xc6, 0x83,
	0xe5, 0x63, 0xeb, 0x2f, 0x15, 0x2d, 0xff, 0x44, 0xfd, 0x05, 0xea, 0x7b, 0x73, 0xfa, 0xc7, 0x9a,
	0xbd, 0x2a, 0xa1, 0xff, 0x77, 0x8b, 0x1c, 0xcd, 0x6f, 0xa2, 0x22, 0x37, 0xba, 0x80, 0xfa, 0x2a,
	0x5a, 0x3b, 0xd9, 0x1f, 0xac, 0x9d, 0xec, 0x6b, 0x07, 0xe7, 0xc6, 0xda, 0xc1, 0xb9, 0x6e, 0x8a,
	0xb4, 0x3e, 0x7a, 0x8a, 0x3c, 0x5c, 0x3b, 0x45, 0xaa, 0xd6, 0xdb, 0x5c, 0xb4, 0xde, 0xbf, 0xb4,
	0x55, 0xb8, 0x82, 0xfe, 0x57, 0x5b, 0x6d, 0xad, 0xb6, 0x55, 0xc3, 0x81, 0x0b, 0xb7, 0xcc, 0x7f,
	0x1f, 0xb8, 0xf6, 0xe2, 0x57, 0x5d, 0x1c, 0xb8, 0x95, 0xe3, 0x41, 0x56, 0x8f, 0xc7, 0x37, 0x8e,
	0x74, 0xa2, 0xc5, 0xbb, 0x82, 0x02, 0x39, 0xad, 0x3e, 0x7f, 0x28, 0x9c, 0xca, 0x84, 0x5b, 0x7e,
	0x9d, 0xd0, 0xfe, 0xe5, 0xd2, 0x1b, 0xe4, 0xb2, 0xf1, 0xfd, 0x71, 0x7a, 0xde, 0xac, 0xb9, 0x77,
	0x32, 0x46, 0x8f, 0xf0, 0x49, 0xf3, 0xed, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x4a, 0x3c,
	0x08, 0x03, 0x09, 0x00, 0x00,
}
