# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.estimateAPI_pb2 as estimateAPI__pb2


class EstimatePowerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EstimatePowerService = channel.unary_unary(
                '/estimate.EstimatePower/EstimatePowerService',
                request_serializer=estimateAPI__pb2.EstimateRequestMessage.SerializeToString,
                response_deserializer=estimateAPI__pb2.EstimateResponseMessage.FromString,
                )


class EstimatePowerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EstimatePowerService(self, request, context):
        """Change this to stream response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EstimatePowerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EstimatePowerService': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimatePowerService,
                    request_deserializer=estimateAPI__pb2.EstimateRequestMessage.FromString,
                    response_serializer=estimateAPI__pb2.EstimateResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'estimate.EstimatePower', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EstimatePower(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EstimatePowerService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/estimate.EstimatePower/EstimatePowerService',
            estimateAPI__pb2.EstimateRequestMessage.SerializeToString,
            estimateAPI__pb2.EstimateResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
