# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: estimateAPI.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='estimateAPI.proto',
  package='estimate',
  syntax='proto3',
  serialized_options=b'Z:github.com/nicholasbunn/masters/src/fetchDataService/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x65stimateAPI.proto\x12\x08\x65stimate\"\x91\x03\n\x16\x45stimateRequestMessage\x12\x1d\n\x15port_prop_motor_speed\x18\x01 \x03(\x02\x12\x1d\n\x15stbd_prop_motor_speed\x18\x02 \x03(\x02\x12\x1c\n\x14propeller_pitch_port\x18\x03 \x03(\x02\x12\x1c\n\x14propeller_pitch_stbd\x18\x04 \x03(\x02\x12\x0b\n\x03sog\x18\x05 \x03(\x02\x12\x1f\n\x17wind_direction_relative\x18\x06 \x03(\x02\x12\x12\n\nwind_speed\x18\x07 \x03(\x02\x12\x17\n\x0f\x62\x65\x61ufort_number\x18\x08 \x03(\x02\x12\x16\n\x0ewave_direction\x18\t \x03(\x02\x12\x13\n\x0bwave_length\x18\n \x03(\x02\x12\x18\n\x10motor_power_port\x18\x0b \x03(\x02\x12\x18\n\x10motor_power_stbd\x18\x0c \x03(\x02\x12\x14\n\x0coriginal_sog\x18\r \x03(\x02\x12+\n\nmodel_type\x18\x0e \x01(\x0e\x32\x17.estimate.ModelTypeEnum\"b\n\x17\x45stimateResponseMessage\x12\x16\n\x0epower_estimate\x18\x01 \x03(\x02\x12\x14\n\x0cpower_actual\x18\x02 \x03(\x02\x12\x19\n\x11speed_over_ground\x18\x03 \x03(\x02*4\n\rModelTypeEnum\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tOPENWATER\x10\x01\x12\x07\n\x03ICE\x10\x02\x32l\n\rEstimatePower\x12[\n\x14\x45stimatePowerService\x12 .estimate.EstimateRequestMessage\x1a!.estimate.EstimateResponseMessageB<Z:github.com/nicholasbunn/masters/src/fetchDataService/protob\x06proto3'
)

_MODELTYPEENUM = _descriptor.EnumDescriptor(
  name='ModelTypeEnum',
  full_name='estimate.ModelTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPENWATER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ICE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=535,
  serialized_end=587,
)
_sym_db.RegisterEnumDescriptor(_MODELTYPEENUM)

ModelTypeEnum = enum_type_wrapper.EnumTypeWrapper(_MODELTYPEENUM)
UNKNOWN = 0
OPENWATER = 1
ICE = 2



_ESTIMATEREQUESTMESSAGE = _descriptor.Descriptor(
  name='EstimateRequestMessage',
  full_name='estimate.EstimateRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='port_prop_motor_speed', full_name='estimate.EstimateRequestMessage.port_prop_motor_speed', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stbd_prop_motor_speed', full_name='estimate.EstimateRequestMessage.stbd_prop_motor_speed', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='propeller_pitch_port', full_name='estimate.EstimateRequestMessage.propeller_pitch_port', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='propeller_pitch_stbd', full_name='estimate.EstimateRequestMessage.propeller_pitch_stbd', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sog', full_name='estimate.EstimateRequestMessage.sog', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wind_direction_relative', full_name='estimate.EstimateRequestMessage.wind_direction_relative', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wind_speed', full_name='estimate.EstimateRequestMessage.wind_speed', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='beaufort_number', full_name='estimate.EstimateRequestMessage.beaufort_number', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wave_direction', full_name='estimate.EstimateRequestMessage.wave_direction', index=8,
      number=9, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wave_length', full_name='estimate.EstimateRequestMessage.wave_length', index=9,
      number=10, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_power_port', full_name='estimate.EstimateRequestMessage.motor_power_port', index=10,
      number=11, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_power_stbd', full_name='estimate.EstimateRequestMessage.motor_power_stbd', index=11,
      number=12, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='original_sog', full_name='estimate.EstimateRequestMessage.original_sog', index=12,
      number=13, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_type', full_name='estimate.EstimateRequestMessage.model_type', index=13,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=433,
)


_ESTIMATERESPONSEMESSAGE = _descriptor.Descriptor(
  name='EstimateResponseMessage',
  full_name='estimate.EstimateResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='power_estimate', full_name='estimate.EstimateResponseMessage.power_estimate', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power_actual', full_name='estimate.EstimateResponseMessage.power_actual', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_over_ground', full_name='estimate.EstimateResponseMessage.speed_over_ground', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=533,
)

_ESTIMATEREQUESTMESSAGE.fields_by_name['model_type'].enum_type = _MODELTYPEENUM
DESCRIPTOR.message_types_by_name['EstimateRequestMessage'] = _ESTIMATEREQUESTMESSAGE
DESCRIPTOR.message_types_by_name['EstimateResponseMessage'] = _ESTIMATERESPONSEMESSAGE
DESCRIPTOR.enum_types_by_name['ModelTypeEnum'] = _MODELTYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstimateRequestMessage = _reflection.GeneratedProtocolMessageType('EstimateRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _ESTIMATEREQUESTMESSAGE,
  '__module__' : 'estimateAPI_pb2'
  # @@protoc_insertion_point(class_scope:estimate.EstimateRequestMessage)
  })
_sym_db.RegisterMessage(EstimateRequestMessage)

EstimateResponseMessage = _reflection.GeneratedProtocolMessageType('EstimateResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _ESTIMATERESPONSEMESSAGE,
  '__module__' : 'estimateAPI_pb2'
  # @@protoc_insertion_point(class_scope:estimate.EstimateResponseMessage)
  })
_sym_db.RegisterMessage(EstimateResponseMessage)


DESCRIPTOR._options = None

_ESTIMATEPOWER = _descriptor.ServiceDescriptor(
  name='EstimatePower',
  full_name='estimate.EstimatePower',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=589,
  serialized_end=697,
  methods=[
  _descriptor.MethodDescriptor(
    name='EstimatePowerService',
    full_name='estimate.EstimatePower.EstimatePowerService',
    index=0,
    containing_service=None,
    input_type=_ESTIMATEREQUESTMESSAGE,
    output_type=_ESTIMATERESPONSEMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ESTIMATEPOWER)

DESCRIPTOR.services_by_name['EstimatePower'] = _ESTIMATEPOWER

# @@protoc_insertion_point(module_scope)
