// Code generated by protoc-gen-go. DO NOT EDIT.
// source: estimateService/proto/estimateAPI.proto

package estimate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ModelTypeEnum int32

const (
	ModelTypeEnum_UNKNOWN   ModelTypeEnum = 0
	ModelTypeEnum_OPENWATER ModelTypeEnum = 1
	ModelTypeEnum_ICE       ModelTypeEnum = 2
)

var ModelTypeEnum_name = map[int32]string{
	0: "UNKNOWN",
	1: "OPENWATER",
	2: "ICE",
}

var ModelTypeEnum_value = map[string]int32{
	"UNKNOWN":   0,
	"OPENWATER": 1,
	"ICE":       2,
}

func (x ModelTypeEnum) String() string {
	return proto.EnumName(ModelTypeEnum_name, int32(x))
}

func (ModelTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_afc4875b92654bbc, []int{0}
}

type EstimateRequestMessage struct {
	PortPropMotorSpeed    []float32     `protobuf:"fixed32,1,rep,packed,name=port_prop_motor_speed,json=portPropMotorSpeed,proto3" json:"port_prop_motor_speed,omitempty"`
	StbdPropMotorSpeed    []float32     `protobuf:"fixed32,2,rep,packed,name=stbd_prop_motor_speed,json=stbdPropMotorSpeed,proto3" json:"stbd_prop_motor_speed,omitempty"`
	PropellerPitchPort    []float32     `protobuf:"fixed32,3,rep,packed,name=propeller_pitch_port,json=propellerPitchPort,proto3" json:"propeller_pitch_port,omitempty"`
	PropellerPitchStbd    []float32     `protobuf:"fixed32,4,rep,packed,name=propeller_pitch_stbd,json=propellerPitchStbd,proto3" json:"propeller_pitch_stbd,omitempty"`
	Sog                   []float32     `protobuf:"fixed32,5,rep,packed,name=sog,proto3" json:"sog,omitempty"`
	WindDirectionRelative []float32     `protobuf:"fixed32,6,rep,packed,name=wind_direction_relative,json=windDirectionRelative,proto3" json:"wind_direction_relative,omitempty"`
	WindSpeed             []float32     `protobuf:"fixed32,7,rep,packed,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	BeaufortNumber        []float32     `protobuf:"fixed32,8,rep,packed,name=beaufort_number,json=beaufortNumber,proto3" json:"beaufort_number,omitempty"`
	WaveDirection         []float32     `protobuf:"fixed32,9,rep,packed,name=wave_direction,json=waveDirection,proto3" json:"wave_direction,omitempty"`
	WaveLength            []float32     `protobuf:"fixed32,10,rep,packed,name=wave_length,json=waveLength,proto3" json:"wave_length,omitempty"`
	MotorPowerPort        []float32     `protobuf:"fixed32,11,rep,packed,name=motor_power_port,json=motorPowerPort,proto3" json:"motor_power_port,omitempty"`
	MotorPowerStbd        []float32     `protobuf:"fixed32,12,rep,packed,name=motor_power_stbd,json=motorPowerStbd,proto3" json:"motor_power_stbd,omitempty"`
	OriginalSog           []float32     `protobuf:"fixed32,13,rep,packed,name=original_sog,json=originalSog,proto3" json:"original_sog,omitempty"`
	ModelType             ModelTypeEnum `protobuf:"varint,14,opt,name=model_type,json=modelType,proto3,enum=estimate.ModelTypeEnum" json:"model_type,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}      `json:"-"`
	XXX_unrecognized      []byte        `json:"-"`
	XXX_sizecache         int32         `json:"-"`
}

func (m *EstimateRequestMessage) Reset()         { *m = EstimateRequestMessage{} }
func (m *EstimateRequestMessage) String() string { return proto.CompactTextString(m) }
func (*EstimateRequestMessage) ProtoMessage()    {}
func (*EstimateRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_afc4875b92654bbc, []int{0}
}

func (m *EstimateRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimateRequestMessage.Unmarshal(m, b)
}
func (m *EstimateRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimateRequestMessage.Marshal(b, m, deterministic)
}
func (m *EstimateRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimateRequestMessage.Merge(m, src)
}
func (m *EstimateRequestMessage) XXX_Size() int {
	return xxx_messageInfo_EstimateRequestMessage.Size(m)
}
func (m *EstimateRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimateRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EstimateRequestMessage proto.InternalMessageInfo

func (m *EstimateRequestMessage) GetPortPropMotorSpeed() []float32 {
	if m != nil {
		return m.PortPropMotorSpeed
	}
	return nil
}

func (m *EstimateRequestMessage) GetStbdPropMotorSpeed() []float32 {
	if m != nil {
		return m.StbdPropMotorSpeed
	}
	return nil
}

func (m *EstimateRequestMessage) GetPropellerPitchPort() []float32 {
	if m != nil {
		return m.PropellerPitchPort
	}
	return nil
}

func (m *EstimateRequestMessage) GetPropellerPitchStbd() []float32 {
	if m != nil {
		return m.PropellerPitchStbd
	}
	return nil
}

func (m *EstimateRequestMessage) GetSog() []float32 {
	if m != nil {
		return m.Sog
	}
	return nil
}

func (m *EstimateRequestMessage) GetWindDirectionRelative() []float32 {
	if m != nil {
		return m.WindDirectionRelative
	}
	return nil
}

func (m *EstimateRequestMessage) GetWindSpeed() []float32 {
	if m != nil {
		return m.WindSpeed
	}
	return nil
}

func (m *EstimateRequestMessage) GetBeaufortNumber() []float32 {
	if m != nil {
		return m.BeaufortNumber
	}
	return nil
}

func (m *EstimateRequestMessage) GetWaveDirection() []float32 {
	if m != nil {
		return m.WaveDirection
	}
	return nil
}

func (m *EstimateRequestMessage) GetWaveLength() []float32 {
	if m != nil {
		return m.WaveLength
	}
	return nil
}

func (m *EstimateRequestMessage) GetMotorPowerPort() []float32 {
	if m != nil {
		return m.MotorPowerPort
	}
	return nil
}

func (m *EstimateRequestMessage) GetMotorPowerStbd() []float32 {
	if m != nil {
		return m.MotorPowerStbd
	}
	return nil
}

func (m *EstimateRequestMessage) GetOriginalSog() []float32 {
	if m != nil {
		return m.OriginalSog
	}
	return nil
}

func (m *EstimateRequestMessage) GetModelType() ModelTypeEnum {
	if m != nil {
		return m.ModelType
	}
	return ModelTypeEnum_UNKNOWN
}

type EstimateResponseMessage struct {
	PowerEstimate        []float32 `protobuf:"fixed32,1,rep,packed,name=power_estimate,json=powerEstimate,proto3" json:"power_estimate,omitempty"`
	PowerActual          []float32 `protobuf:"fixed32,2,rep,packed,name=power_actual,json=powerActual,proto3" json:"power_actual,omitempty"`
	SpeedOverGround      []float32 `protobuf:"fixed32,3,rep,packed,name=speed_over_ground,json=speedOverGround,proto3" json:"speed_over_ground,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EstimateResponseMessage) Reset()         { *m = EstimateResponseMessage{} }
func (m *EstimateResponseMessage) String() string { return proto.CompactTextString(m) }
func (*EstimateResponseMessage) ProtoMessage()    {}
func (*EstimateResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_afc4875b92654bbc, []int{1}
}

func (m *EstimateResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimateResponseMessage.Unmarshal(m, b)
}
func (m *EstimateResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimateResponseMessage.Marshal(b, m, deterministic)
}
func (m *EstimateResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimateResponseMessage.Merge(m, src)
}
func (m *EstimateResponseMessage) XXX_Size() int {
	return xxx_messageInfo_EstimateResponseMessage.Size(m)
}
func (m *EstimateResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimateResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EstimateResponseMessage proto.InternalMessageInfo

func (m *EstimateResponseMessage) GetPowerEstimate() []float32 {
	if m != nil {
		return m.PowerEstimate
	}
	return nil
}

func (m *EstimateResponseMessage) GetPowerActual() []float32 {
	if m != nil {
		return m.PowerActual
	}
	return nil
}

func (m *EstimateResponseMessage) GetSpeedOverGround() []float32 {
	if m != nil {
		return m.SpeedOverGround
	}
	return nil
}

func init() {
	proto.RegisterEnum("estimate.ModelTypeEnum", ModelTypeEnum_name, ModelTypeEnum_value)
	proto.RegisterType((*EstimateRequestMessage)(nil), "estimate.EstimateRequestMessage")
	proto.RegisterType((*EstimateResponseMessage)(nil), "estimate.EstimateResponseMessage")
}

func init() {
	proto.RegisterFile("estimateService/proto/estimateAPI.proto", fileDescriptor_afc4875b92654bbc)
}

var fileDescriptor_afc4875b92654bbc = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x5f, 0x6f, 0x12, 0x41,
	0x14, 0xc5, 0x05, 0x6a, 0x29, 0x97, 0x2e, 0xc5, 0x49, 0x2b, 0x1b, 0x13, 0x23, 0x6d, 0xd2, 0x94,
	0xf4, 0x81, 0x6a, 0x35, 0xbe, 0x13, 0x25, 0xa6, 0x51, 0x60, 0x03, 0x35, 0x7d, 0xf0, 0x61, 0xb3,
	0xb0, 0x57, 0xba, 0xc9, 0xee, 0xce, 0x38, 0x3b, 0x0b, 0xe9, 0xa7, 0xf0, 0x83, 0xfa, 0x25, 0xcc,
	0xbd, 0xbb, 0x23, 0x01, 0x79, 0x63, 0x7f, 0xe7, 0x9c, 0xf9, 0x73, 0xb8, 0x03, 0x57, 0x98, 0x99,
	0x28, 0x09, 0x0c, 0xce, 0x50, 0xaf, 0xa2, 0x05, 0xde, 0x28, 0x2d, 0x8d, 0xbc, 0xb1, 0x74, 0xe0,
	0xdd, 0xf5, 0x99, 0x88, 0x23, 0x8b, 0x2e, 0xfe, 0x1c, 0xc0, 0xcb, 0x61, 0xf9, 0x31, 0xc5, 0x5f,
	0x39, 0x66, 0x66, 0x84, 0x59, 0x16, 0x2c, 0x51, 0xbc, 0x83, 0x33, 0x25, 0xb5, 0xf1, 0x95, 0x96,
	0xca, 0x4f, 0xa4, 0x91, 0xda, 0xcf, 0x14, 0x62, 0xe8, 0x56, 0xba, 0xb5, 0x5e, 0x75, 0x2a, 0x48,
	0xf4, 0xb4, 0x54, 0x23, 0x92, 0x66, 0xa4, 0x50, 0x24, 0x33, 0xf3, 0xf0, 0xff, 0x48, 0xb5, 0x88,
	0x90, 0xb8, 0x13, 0x79, 0x0b, 0xa7, 0xe4, 0xc6, 0x38, 0x46, 0xed, 0xab, 0xc8, 0x2c, 0x1e, 0x7d,
	0x5a, 0xd8, 0xad, 0x95, 0x9b, 0x58, 0xcd, 0x23, 0xc9, 0x93, 0xda, 0xec, 0x4b, 0xd0, 0xba, 0xee,
	0xc1, 0xbe, 0xc4, 0xcc, 0xcc, 0x43, 0xd1, 0x86, 0x5a, 0x26, 0x97, 0xee, 0x73, 0x36, 0xd0, 0x4f,
	0xf1, 0x11, 0x3a, 0xeb, 0x28, 0x0d, 0xfd, 0x30, 0xd2, 0xb8, 0x30, 0x91, 0x4c, 0x7d, 0x8d, 0x71,
	0x60, 0xa2, 0x15, 0xba, 0x87, 0xec, 0x3a, 0x23, 0xf9, 0xb3, 0x55, 0xa7, 0xa5, 0x28, 0x5e, 0x03,
	0x70, 0xae, 0xb8, 0x55, 0x9d, 0xad, 0x0d, 0x22, 0xc5, 0x65, 0xae, 0xe0, 0x64, 0x8e, 0x41, 0xfe,
	0x93, 0x6a, 0x4b, 0xf3, 0x64, 0x8e, 0xda, 0x3d, 0x62, 0x4f, 0xcb, 0xe2, 0x31, 0x53, 0x71, 0x09,
	0xad, 0x75, 0xb0, 0xc2, 0xcd, 0xfe, 0x6e, 0x83, 0x7d, 0x0e, 0xd1, 0x7f, 0xdb, 0x8a, 0x37, 0xd0,
	0x64, 0x5b, 0x8c, 0xe9, 0xd2, 0x3c, 0xba, 0xc0, 0x1e, 0x20, 0xf4, 0x8d, 0x89, 0xe8, 0x41, 0xbb,
	0xa8, 0x59, 0xc9, 0x35, 0xb5, 0x41, 0xcd, 0x35, 0x8b, 0x1d, 0x99, 0x7b, 0x84, 0xb9, 0xb5, 0x1d,
	0x27, 0x37, 0x76, 0xbc, 0xeb, 0xe4, 0xb6, 0xce, 0xe1, 0x58, 0xea, 0x68, 0x19, 0xa5, 0x41, 0xec,
	0x53, 0x6d, 0x0e, 0xbb, 0x9a, 0x96, 0xcd, 0xb8, 0x3e, 0x48, 0x64, 0x88, 0xb1, 0x6f, 0x9e, 0x14,
	0xba, 0xad, 0x6e, 0xa5, 0xd7, 0xba, 0xed, 0xf4, 0xed, 0x50, 0xf5, 0x47, 0xa4, 0xdd, 0x3f, 0x29,
	0x1c, 0xa6, 0x79, 0x32, 0x6d, 0x24, 0xf6, 0xf3, 0xe2, 0x77, 0x05, 0x3a, 0x9b, 0x69, 0xcb, 0x94,
	0x4c, 0x33, 0xb4, 0xe3, 0x76, 0x09, 0xad, 0xe2, 0x68, 0x76, 0x99, 0x72, 0xce, 0x1c, 0xa6, 0x36,
	0x45, 0xa7, 0x2b, 0x6c, 0xc1, 0xc2, 0xe4, 0x41, 0x5c, 0x4e, 0x56, 0x93, 0xd9, 0x80, 0x91, 0xb8,
	0x86, 0x17, 0xfc, 0xff, 0xf8, 0x72, 0x85, 0xda, 0x5f, 0x6a, 0x99, 0xa7, 0x61, 0x39, 0x4f, 0x27,
	0x2c, 0x4c, 0x56, 0xa8, 0xbf, 0x30, 0xbe, 0xfe, 0x00, 0xce, 0xd6, 0x69, 0x45, 0x13, 0xea, 0xdf,
	0xc7, 0x5f, 0xc7, 0x93, 0x87, 0x71, 0xfb, 0x99, 0x70, 0xa0, 0x31, 0xf1, 0x86, 0xe3, 0x87, 0xc1,
	0xfd, 0x70, 0xda, 0xae, 0x88, 0x3a, 0xd4, 0xee, 0x3e, 0x0d, 0xdb, 0xd5, 0xdb, 0x18, 0x1c, 0x7b,
	0x20, 0xee, 0x4d, 0xfc, 0x80, 0xd3, 0x2d, 0x50, 0x3e, 0x40, 0xd1, 0xdd, 0x94, 0xb2, 0xff, 0x95,
	0xbd, 0x3a, 0xdf, 0xe7, 0xd8, 0x6a, 0x66, 0x7e, 0xc8, 0x8f, 0xf6, 0xfd, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x5c, 0x31, 0x7a, 0x25, 0xdf, 0x03, 0x00, 0x00,
}
