// Code generated by protoc-gen-go. DO NOT EDIT.
// source: desktopGateway/proto/desktopGatewayAPI.proto

package desktopGateway

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Messages for the estimation service package
type EstimationRequest struct {
	Bla                  string   `protobuf:"bytes,1,opt,name=bla,proto3" json:"bla,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstimationRequest) Reset()         { *m = EstimationRequest{} }
func (m *EstimationRequest) String() string { return proto.CompactTextString(m) }
func (*EstimationRequest) ProtoMessage()    {}
func (*EstimationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4293fa92ac258706, []int{0}
}

func (m *EstimationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimationRequest.Unmarshal(m, b)
}
func (m *EstimationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimationRequest.Marshal(b, m, deterministic)
}
func (m *EstimationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimationRequest.Merge(m, src)
}
func (m *EstimationRequest) XXX_Size() int {
	return xxx_messageInfo_EstimationRequest.Size(m)
}
func (m *EstimationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EstimationRequest proto.InternalMessageInfo

func (m *EstimationRequest) GetBla() string {
	if m != nil {
		return m.Bla
	}
	return ""
}

type CostEstimationRespose struct {
	Blabla               string   `protobuf:"bytes,1,opt,name=blabla,proto3" json:"blabla,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CostEstimationRespose) Reset()         { *m = CostEstimationRespose{} }
func (m *CostEstimationRespose) String() string { return proto.CompactTextString(m) }
func (*CostEstimationRespose) ProtoMessage()    {}
func (*CostEstimationRespose) Descriptor() ([]byte, []int) {
	return fileDescriptor_4293fa92ac258706, []int{1}
}

func (m *CostEstimationRespose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CostEstimationRespose.Unmarshal(m, b)
}
func (m *CostEstimationRespose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CostEstimationRespose.Marshal(b, m, deterministic)
}
func (m *CostEstimationRespose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CostEstimationRespose.Merge(m, src)
}
func (m *CostEstimationRespose) XXX_Size() int {
	return xxx_messageInfo_CostEstimationRespose.Size(m)
}
func (m *CostEstimationRespose) XXX_DiscardUnknown() {
	xxx_messageInfo_CostEstimationRespose.DiscardUnknown(m)
}

var xxx_messageInfo_CostEstimationRespose proto.InternalMessageInfo

func (m *CostEstimationRespose) GetBlabla() string {
	if m != nil {
		return m.Blabla
	}
	return ""
}

type PowerEstimationResponse struct {
	PowerEstimate        []float32 `protobuf:"fixed32,1,rep,packed,name=powerEstimate,proto3" json:"powerEstimate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PowerEstimationResponse) Reset()         { *m = PowerEstimationResponse{} }
func (m *PowerEstimationResponse) String() string { return proto.CompactTextString(m) }
func (*PowerEstimationResponse) ProtoMessage()    {}
func (*PowerEstimationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4293fa92ac258706, []int{2}
}

func (m *PowerEstimationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PowerEstimationResponse.Unmarshal(m, b)
}
func (m *PowerEstimationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PowerEstimationResponse.Marshal(b, m, deterministic)
}
func (m *PowerEstimationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PowerEstimationResponse.Merge(m, src)
}
func (m *PowerEstimationResponse) XXX_Size() int {
	return xxx_messageInfo_PowerEstimationResponse.Size(m)
}
func (m *PowerEstimationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PowerEstimationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PowerEstimationResponse proto.InternalMessageInfo

func (m *PowerEstimationResponse) GetPowerEstimate() []float32 {
	if m != nil {
		return m.PowerEstimate
	}
	return nil
}

// Messages for the frontend login
type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	HashedPassword       string   `protobuf:"bytes,2,opt,name=hashedPassword,proto3" json:"hashedPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4293fa92ac258706, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetHashedPassword() string {
	if m != nil {
		return m.HashedPassword
	}
	return ""
}

type LoginResponse struct {
	Permissions          string   `protobuf:"bytes,1,opt,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4293fa92ac258706, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetPermissions() string {
	if m != nil {
		return m.Permissions
	}
	return ""
}

func init() {
	proto.RegisterType((*EstimationRequest)(nil), "EstimationRequest")
	proto.RegisterType((*CostEstimationRespose)(nil), "CostEstimationRespose")
	proto.RegisterType((*PowerEstimationResponse)(nil), "PowerEstimationResponse")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
}

func init() {
	proto.RegisterFile("desktopGateway/proto/desktopGatewayAPI.proto", fileDescriptor_4293fa92ac258706)
}

var fileDescriptor_4293fa92ac258706 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x8b, 0x45, 0x47, 0x5b, 0xda, 0x05, 0x6b, 0xe8, 0xa9, 0x44, 0x5b, 0x7a, 0x90,
	0x0d, 0x56, 0xf0, 0x22, 0x28, 0x55, 0x44, 0x04, 0x0f, 0x21, 0xbd, 0x79, 0xdb, 0x98, 0xc1, 0x2e,
	0x36, 0xd9, 0xb8, 0xb3, 0x35, 0xf8, 0x2e, 0x3e, 0xac, 0x18, 0x96, 0x9a, 0xa4, 0xf1, 0x96, 0xf9,
	0x32, 0xfb, 0xef, 0xcc, 0xc7, 0xc2, 0x79, 0x8c, 0xf4, 0x6e, 0x54, 0xf6, 0x28, 0x0c, 0xe6, 0xe2,
	0xcb, 0xcf, 0xb4, 0x32, 0xca, 0xaf, 0xc2, 0x45, 0xf0, 0xc4, 0x0b, 0xee, 0x4d, 0x60, 0xf0, 0x40,
	0x46, 0x26, 0xc2, 0x48, 0x95, 0x86, 0xf8, 0xb1, 0x41, 0x32, 0xac, 0x0f, 0xed, 0x68, 0x2d, 0x5c,
	0x67, 0xec, 0xcc, 0x0e, 0xc2, 0xdf, 0x4f, 0xcf, 0x87, 0xe3, 0x7b, 0x45, 0xa6, 0xdc, 0x4a, 0x99,
	0x22, 0x64, 0x43, 0xe8, 0x44, 0x6b, 0xf1, 0xd7, 0x6d, 0x2b, 0xef, 0x16, 0x4e, 0x02, 0x95, 0xa3,
	0xae, 0x9d, 0x48, 0x09, 0xd9, 0x19, 0x74, 0xb3, 0xd2, 0x2f, 0x74, 0x9d, 0x71, 0x7b, 0xd6, 0x0a,
	0xab, 0xd0, 0x0b, 0xe1, 0xe8, 0x59, 0xbd, 0xc9, 0xed, 0x4c, 0x23, 0xd8, 0xdf, 0x10, 0xea, 0x54,
	0x24, 0x68, 0xaf, 0xda, 0xd6, 0x6c, 0x0a, 0xbd, 0x95, 0xa0, 0x15, 0xc6, 0x81, 0x20, 0xca, 0x95,
	0x8e, 0xdd, 0x56, 0xd1, 0x51, 0xa3, 0xde, 0x05, 0x74, 0x6d, 0xa6, 0x1d, 0x65, 0x0c, 0x87, 0x19,
	0xea, 0x44, 0x12, 0x49, 0x95, 0x92, 0xcd, 0x2d, 0xa3, 0xf9, 0xb7, 0xb3, 0xb3, 0xc8, 0x12, 0xf5,
	0xa7, 0x7c, 0x45, 0x62, 0x37, 0xd0, 0xaf, 0x4a, 0x59, 0x06, 0x8c, 0xf1, 0x1d, 0x9d, 0xa3, 0x21,
	0x6f, 0x76, 0xb7, 0x80, 0x41, 0x3d, 0xba, 0x39, 0xc0, 0xe5, 0xff, 0xb8, 0x9c, 0x5f, 0x59, 0x4b,
	0x76, 0x26, 0x36, 0x85, 0xbd, 0xa2, 0x66, 0x5d, 0x5e, 0xb6, 0x37, 0xea, 0xf1, 0xca, 0xe2, 0x77,
	0x93, 0x97, 0xd3, 0xa6, 0x67, 0x72, 0x5d, 0x85, 0x51, 0xa7, 0xa0, 0x97, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xe1, 0x37, 0x04, 0xb0, 0x54, 0x02, 0x00, 0x00,
}
