// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package desktopGateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PowerEstimationServicesClient is the client API for PowerEstimationServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PowerEstimationServicesClient interface {
	CostEstimationSP(ctx context.Context, in *EstimationRequest, opts ...grpc.CallOption) (*CostEstimationRespose, error)
	PowerEstimationSP(ctx context.Context, in *EstimationRequest, opts ...grpc.CallOption) (*PowerEstimationResponse, error)
}

type powerEstimationServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewPowerEstimationServicesClient(cc grpc.ClientConnInterface) PowerEstimationServicesClient {
	return &powerEstimationServicesClient{cc}
}

func (c *powerEstimationServicesClient) CostEstimationSP(ctx context.Context, in *EstimationRequest, opts ...grpc.CallOption) (*CostEstimationRespose, error) {
	out := new(CostEstimationRespose)
	err := c.cc.Invoke(ctx, "/PowerEstimationServices/CostEstimationSP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powerEstimationServicesClient) PowerEstimationSP(ctx context.Context, in *EstimationRequest, opts ...grpc.CallOption) (*PowerEstimationResponse, error) {
	out := new(PowerEstimationResponse)
	err := c.cc.Invoke(ctx, "/PowerEstimationServices/PowerEstimationSP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PowerEstimationServicesServer is the server API for PowerEstimationServices service.
// All implementations must embed UnimplementedPowerEstimationServicesServer
// for forward compatibility
type PowerEstimationServicesServer interface {
	CostEstimationSP(context.Context, *EstimationRequest) (*CostEstimationRespose, error)
	PowerEstimationSP(context.Context, *EstimationRequest) (*PowerEstimationResponse, error)
	mustEmbedUnimplementedPowerEstimationServicesServer()
}

// UnimplementedPowerEstimationServicesServer must be embedded to have forward compatible implementations.
type UnimplementedPowerEstimationServicesServer struct {
}

func (UnimplementedPowerEstimationServicesServer) CostEstimationSP(context.Context, *EstimationRequest) (*CostEstimationRespose, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CostEstimationSP not implemented")
}
func (UnimplementedPowerEstimationServicesServer) PowerEstimationSP(context.Context, *EstimationRequest) (*PowerEstimationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PowerEstimationSP not implemented")
}
func (UnimplementedPowerEstimationServicesServer) mustEmbedUnimplementedPowerEstimationServicesServer() {
}

// UnsafePowerEstimationServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PowerEstimationServicesServer will
// result in compilation errors.
type UnsafePowerEstimationServicesServer interface {
	mustEmbedUnimplementedPowerEstimationServicesServer()
}

func RegisterPowerEstimationServicesServer(s grpc.ServiceRegistrar, srv PowerEstimationServicesServer) {
	s.RegisterService(&PowerEstimationServices_ServiceDesc, srv)
}

func _PowerEstimationServices_CostEstimationSP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerEstimationServicesServer).CostEstimationSP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PowerEstimationServices/CostEstimationSP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerEstimationServicesServer).CostEstimationSP(ctx, req.(*EstimationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowerEstimationServices_PowerEstimationSP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerEstimationServicesServer).PowerEstimationSP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PowerEstimationServices/PowerEstimationSP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerEstimationServicesServer).PowerEstimationSP(ctx, req.(*EstimationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PowerEstimationServices_ServiceDesc is the grpc.ServiceDesc for PowerEstimationServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PowerEstimationServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PowerEstimationServices",
	HandlerType: (*PowerEstimationServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CostEstimationSP",
			Handler:    _PowerEstimationServices_CostEstimationSP_Handler,
		},
		{
			MethodName: "PowerEstimationSP",
			Handler:    _PowerEstimationServices_PowerEstimationSP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desktopGateway/proto/desktopGatewayAPI.proto",
}

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type loginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginServiceClient(cc grpc.ClientConnInterface) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/LoginService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the server API for LoginService service.
// All implementations must embed UnimplementedLoginServiceServer
// for forward compatibility
type LoginServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedLoginServiceServer()
}

// UnimplementedLoginServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLoginServiceServer struct {
}

func (UnimplementedLoginServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedLoginServiceServer) mustEmbedUnimplementedLoginServiceServer() {}

// UnsafeLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginServiceServer will
// result in compilation errors.
type UnsafeLoginServiceServer interface {
	mustEmbedUnimplementedLoginServiceServer()
}

func RegisterLoginServiceServer(s grpc.ServiceRegistrar, srv LoginServiceServer) {
	s.RegisterService(&LoginService_ServiceDesc, srv)
}

func _LoginService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LoginService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginService_ServiceDesc is the grpc.ServiceDesc for LoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _LoginService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desktopGateway/proto/desktopGatewayAPI.proto",
}
